### ISSUE TITLE
Rclone mount/mounts crashing/disconnecting from the mount folder/point (panic: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by aniel300** [divyam234/teldrive#117]
Can u take a look at this please? https://forum.rclone.org/t/rclone-mount-mounts-crashing-disconnecting-from-the-mount-folder-point-panic-runtime-error-invalid-memory-address-or-nil-pointer-dereference/44484/1

**Comment by divyam234** [comment]
@aniel300 first thing don't raise issue in rclone forum teldrive it's not associated with official rclone delete it immediately

**Comment by aniel300** [comment]
> @aniel300 first thing don't raise issue in rclone forum teldrive it's not associated with official rclone delete it immediately

sorry i dint mean to upset you and also i dont think i can delete my post.
