### ISSUE TITLE
File deletion

### ISSUE THREAD

**Issue by antoinerzad** [divyam234/teldrive#128]
Hello, I noticed that the files were not really deleted on Telegram, is this normal?

**Comment by divyam234** [comment]
they are deleted hourly through cron jobs.Its intentional  if person  deletes  files accidently he can recover it in that time frame

**Comment by akzzy** [comment]
> they are deleted hourly through cron jobs.Its intentional if person deletes files accidently he can recover it in that time frame

How do i recover deleted files.
