### ISSUE TITLE
Copy download link button

### ISSUE THREAD

**Issue by antoinerzad** [divyam234/teldrive#129]
Hello, i got a problem with the "Copy download link button"
Uploading firefox_CJGlIDFaEw.mp4…

I tried with several browsers without any real change

Thanks !

**Comment by antoinerzad** [comment]
https://github.com/divyam234/teldrive/assets/24781761/06fcb12c-cd56-4044-93f6-63b813efed55

**Comment by antoinerzad** [comment]
I don't know how to explain it but it unlocked itself.

**Comment by MinorX** [comment]
> I don't know how to explain it but it unlocked itself.

IG it works after sometime.
