### ISSUE TITLE
Unable to auth, websocket connection stuck

### ISSUE THREAD

**Issue by deadmerc** [divyam234/teldrive#135]
Hello,

I am not able to login, ws connection just stay in pending.
Tried to reset config, different versions, the same problem, any idea how to fix that?
<img width="1533" alt="image" src="https://github.com/divyam234/teldrive/assets/2972866/0cac59ba-7f58-4834-8e06-59cd822a849a">

**Comment by Linden10** [comment]
Hmm...I wonder what's going on, can you upload the logs? It should be in the main teldrive folder that you're using.
Have you tried logging in with phone num too btw?

**Comment by deadmerc** [comment]
Yeah, I tried to run on raspberry or on laptop, disable all firewall, enable developer mode with all logs "-1", tried to open from phone, the same thing happen, in logs itself no errors no warning

Made a domain with hosts file, nothing working

```
2024/02/15 02:23:38 goose: no migrations to run. current version: 20240120151952
15/02/2024 02:23 AM	INFO	Started server http://localhost:80
15/02/2024 02:23 AM	INFO	/login	{"status": 200, "method": "GET", "path": "/login", "query": "redirect=%2F", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 0.042737682, "time": "2024-02-15T06:23:50Z"}
15/02/2024 02:23 AM	INFO	/assets/index-NKTO0xtB.js	{"status": 200, "method": "GET", "path": "/assets/index-NKTO0xtB.js", "query": "", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 0.018191239, "time": "2024-02-15T06:23:50Z"}
15/02/2024 02:23 AM	INFO	/assets/vendor-pzoFXv7M.js	{"status": 200, "method": "GET", "path": "/assets/vendor-pzoFXv7M.js", "query": "", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 0.20107391, "time": "2024-02-15T06:23:50Z"}
15/02/2024 02:23 AM	INFO	/api/auth/session	{"status": 200, "method": "GET", "path": "/api/auth/session", "query": "", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 0.000122574, "time": "2024-02-15T06:23:50Z"}
15/02/2024 02:23 AM	INFO	/assets/_auth.login.lazy-m5MQObpO.js	{"status": 200, "method": "GET", "path": "/assets/_auth.login.lazy-m5MQObpO.js", "query": "", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 0.042048643, "time": "2024-02-15T06:23:50Z"}
15/02/2024 02:26 AM	INFO	/api/auth/ws	{"status": 200, "method": "GET", "path": "/api/auth/ws", "query": "", "ip": "192.168.88.251", "user-agent": "{removed}", "latency": 130.177127488, "time": "2024-02-15T06:26:00Z"}
```

**Comment by divyam234** [comment]
Are you using teldrive behind nginx or some other server

**Comment by deadmerc** [comment]
> Are you using teldrive behind nginx or some other server

No, direct connection in 3 different places ( laptop, rpi, vps )

**Comment by divyam234** [comment]
Strange phone login is also not working?
I can see connection is successful to websocket

**Comment by deadmerc** [comment]
> Strange phone login is also not working? I can see connection is successful to websocket

No, give a shot here http://152.53.17.162:30500
![IMG_66107F5857B4-1](https://github.com/divyam234/teldrive/assets/2972866/d30b0910-068e-429c-ae96-5ef7c0a79c40)

**Comment by divyam234** [comment]
Yeah there can only be one issue telegram client is not able to make a connect through this ip somehow do one thing try to start server behind vpn see what happens.

**Comment by deadmerc** [comment]
> start server behind vpn see what happens.

I am not really sure how to do it, when I start it locally ( on my laptop ) there should not be any restrictions, but still the same

**Comment by divyam234** [comment]
are use using latest build on 1.2.0 if not pull latest image it was pushes again yesterday.On localhost it shouls assuimg you are able to use telegram app.

**Comment by deadmerc** [comment]
```
tgdrive: ./teldrive version
teldrive 1.1.2
- os/type: darwin
- os/arch: arm64
- go/version: go1.22.0
```

on localhost the same, telegram itself are working fine, browser switch didnt helped also

<img width="1528" alt="image" src="https://github.com/divyam234/teldrive/assets/2972866/1fdcdbe7-be5e-4af7-8bec-dc0826357056">

**Comment by divyam234** [comment]
I think there can be some issue on  macos build  mainly  in  gotd library for telegram although you have tested it on vps which would have used  linux build. I have never seen this issuse before so not sure what can be the cause.

**Comment by deadmerc** [comment]
> I think there can be some issue on macos build mainly in gotd library for telegram although you have tested it on vps which would have used linux build. I have never seen this issuse before so not sure what can be the cause.

I just found the problem, instead of using APP_ID and APP_HASH from actual app, I put bot credentials inside, seems like when app using such credentials telegram answering what I am doing something wrong but not crashing, as when I am changed the APP_ID a bit, only then I start receiving messages about incorrect APP_ID. 

So after I understood my mistake I put inside correct creds and app starts working :D

**Comment by Linden10** [comment]
My what a crazy ride, glad you got help (from the main dev!) and figured it out haha.
