### ISSUE TITLE
huggingface code error

### ISSUE THREAD

**Issue by Pe0xonN** [divyam234/teldrive#136]
![image](https://github.com/divyam234/teldrive/assets/142345756/65243fc5-272a-4cb6-9e8f-36750c97943f)

**Comment by Pe0xonN** [comment]
Does not start

**Comment by Pe0xonN** [comment]
Dockerfile
![image](https://github.com/divyam234/teldrive/assets/142345756/649d4762-964c-4bd6-9d08-3e4dad6f6754)

**Comment by deadmerc** [comment]
Try to change `CMD ["/app/teldrive"]` to `CMD ["/app/teldrive run"]`

**Comment by Pe0xonN** [comment]
> Try to change `CMD ["/app/teldrive"]` to `CMD ["/app/teldrive run"]`

![image](https://github.com/divyam234/teldrive/assets/142345756/c0851fb4-1289-413e-98ee-1e4eb0d706bf)

**Comment by deadmerc** [comment]
Attempt #2

`CMD ["/app/teldrive", "run"]`

**Comment by Pe0xonN** [comment]
![image](https://github.com/divyam234/teldrive/assets/142345756/a396595a-188e-4945-9239-04d00bbb594b)

**Comment by deadmerc** [comment]
Hm, hard to tell, maybe just get rid of first "downloader" stage? As second stage you are using `ubuntu:latest` which can download file also, maybe will help 🤷‍♂️

**Comment by Pe0xonN** [comment]
![image](https://github.com/divyam234/teldrive/assets/142345756/e90a8f4a-2af9-4692-8780-d7d209c1d918)
?

**Comment by deadmerc** [comment]
Send here docker file as text

**Comment by Pe0xonN** [comment]
<html>
<body>

CMD ["/app/teldrive", "run"]# First stage to download the latest release
--
  | FROM alpine as downloader
  |  
  | # Install necessary packages
  | RUN apk update && apk add --no-cache curl jq
  |  
  | # Set the repository owner and repository name
  | ARG REPO_OWNER=divyam234
  | ARG REPO_NAME=teldrive
  |  
  | # GitHub API URL for the latest release
  | ARG API_URL=https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/latest
  |  
  | # Fetch the latest release from GitHub
  | RUN LATEST_RELEASE_TAG=$(curl -s $API_URL \| jq -r '.tag_name') && \
  | wget "https://github.com/$REPO_OWNER/$REPO_NAME/releases/download/$LATEST_RELEASE_TAG/teldrive-$LATEST_RELEASE_TAG-linux-amd64.tar.gz" -O /teldrive.tar.gz
  |  
  | # Second stage to setup the final image
  | FROM ubuntu:latest
  |  
  | # Install necessary packages
  | RUN apt-get update && \
  | apt-get install -y ca-certificates tzdata wget tar curl && \
  | rm -rf /var/lib/apt/lists/*
  |  
  | # Copy the teldrive binary tarball from the downloader stage
  | COPY --from=downloader /teldrive.tar.gz /app/teldrive.tar.gz
  |  
  | WORKDIR /app
  |  
  | # Extract teldrive and setup environment
  | RUN tar -xvf teldrive.tar.gz && \
  | rm teldrive.tar.gz && \
  | chmod -R 777 /app
  |  
  | # Start Teldrive when the container launches
  | CMD ["/app/teldrive", "run"]


</body>
</html>

**Comment by Pe0xonN** [comment]
[Nowy dokument tekstowy.txt](https://github.com/divyam234/teldrive/files/14298340/Nowy.dokument.tekstowy.txt)

**Comment by Pe0xonN** [comment]
![image](https://github.com/divyam234/teldrive/assets/142345756/7b7b47da-2af9-4459-a030-fc27dc511476)


> Btw what are you trying to do as this repo already have docker image `ghcr.io/divyam234/teldrive` ?

**Comment by deadmerc** [comment]
```
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y ca-certificates jq jqtzdata wget tar curl && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

RUN wget $(wget -q -O - https://api.github.com/repos/divyam234/teldrive/releases/latest  |  jq -r '.assets[] | select(.name | contains ("linux-amd64.tar.gz")) | .browser_download_url') -O /teldrive.tar.gz

# Extract teldrive and setup environment
RUN tar -xvf teldrive.tar.gz && \
    rm teldrive.tar.gz && \
    chmod -R 777 /app

# Start Teldrive when the container launches
CMD ["/app/teldrive", "run"]
```

**Comment by Pe0xonN** [comment]
> ```
> FROM ubuntu:latest
> 
> # Install necessary packages
> RUN apt-get update && \
>     apt-get install -y ca-certificates jq jqtzdata wget tar curl && \
>     rm -rf /var/lib/apt/lists/*
> 
> 
> WORKDIR /app
> 
> RUN wget $(wget -q -O - https://api.github.com/repos/divyam234/teldrive/releases/latest  |  jq -r '.assets[] | select(.name | contains ("linux-amd64.tar.gz")) | .browser_download_url') -O teldrive.tar.gz
> 
> # Extract teldrive and setup environment
> RUN tar -xvf teldrive.tar.gz && \
>     rm teldrive.tar.gz && \
>     chmod -R 777 /app
> 
> # Start Teldrive when the container launches
> CMD ["/app/teldrive", "run"]
> ```

![image](https://github.com/divyam234/teldrive/assets/142345756/75a569a8-2675-4c0e-ba93-a4bc0211c4a2)

**Comment by deadmerc** [comment]
```
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y ca-certificates jq wget tar curl && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

RUN wget $(wget -q -O - https://api.github.com/repos/divyam234/teldrive/releases/latest  |  jq -r '.assets[] | select(.name | contains ("linux-amd64.tar.gz")) | .browser_download_url') -O teldrive.tar.gz

# Extract teldrive and setup environment
RUN tar -xvf teldrive.tar.gz && \
    rm teldrive.tar.gz && \
    chmod -R 777 /app

# Start Teldrive when the container launches
CMD ["/app/teldrive", "run"]
```

**Comment by Pe0xonN** [comment]
![Screenshot_20240215-195512](https://github.com/divyam234/teldrive/assets/142345756/3b438078-187f-489f-a9cc-50d235b84a78)

**Comment by deadmerc** [comment]
So, now you need add config, look for required flags

**Comment by Pe0xonN** [comment]
> So, now you need add config, look for required flags

![image](https://github.com/divyam234/teldrive/assets/142345756/6570d0e8-4685-4d2c-8aa3-5f8229302bb6)

**Comment by jojogamezHub** [comment]
> dockerfile
> 
> ```
>   FROM ubuntu:latest
>   
>   RUN apt-get update && \
>       apt-get install -y ca-certificates tzdata wget tar curl
>   
>   WORKDIR /app
>   COPY . .
>   RUN chmod -R 777 /app 
>   
> 
>   RUN --mount=type=secret,id=gist_teldrive,mode=0444,required=true \
>       wget https://github.com/divyam234/teldrive/releases/latest/download/teldrive-1.1.3-linux-amd64.tar.gz -O /app/teldrive.tar.gz && \
>       tar xvf /app/teldrive.tar.gz -C /app  && \
>       wget $(cat /run/secrets/gist_teldrive) -O /app/config.toml && \
>       chmod a+x /app/teldrive && chmod 777 /app/config.toml  && \
>       touch /app/session.db && \
>       chmod 777 /app/session.db
>   
>   RUN chmod a+x /app/start.sh
>   
>   CMD ["./start.sh"]
> ```
> 
> start.sh
> 
> ```
> #!/bin/bash
> /app/teldrive run --config $HOME/app/config.toml 
> ```
> 
> This Worked for me

Yeah, it did work, my only issue now is for some reason, After i successfullly logged in, im still sent back to the log in screen. let me walk you through

Step 1: The main login page shows up
Step 2: I enter phone number and it requests for code
Step 3: I enter code and press login.
Step 4: It loaadsss then it goes back to the log in page.

Nothing showed up on the logs as red flags, hell, the log in was successful.

**Comment by Pe0xonN** [comment]
> > dockerfile
> > ```
> >   FROM ubuntu:latest
> >   
> >   RUN apt-get update && \
> >       apt-get install -y ca-certificates tzdata wget tar curl
> >   
> >   WORKDIR /app
> >   COPY . .
> >   RUN chmod -R 777 /app 
> >   
> > 
> >   RUN --mount=type=secret,id=gist_teldrive,mode=0444,required=true \
> >       wget https://github.com/divyam234/teldrive/releases/latest/download/teldrive-1.1.3-linux-amd64.tar.gz -O /app/teldrive.tar.gz && \
> >       tar xvf /app/teldrive.tar.gz -C /app  && \
> >       wget $(cat /run/secrets/gist_teldrive) -O /app/config.toml && \
> >       chmod a+x /app/teldrive && chmod 777 /app/config.toml  && \
> >       touch /app/session.db && \
> >       chmod 777 /app/session.db
> >   
> >   RUN chmod a+x /app/start.sh
> >   
> >   CMD ["./start.sh"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > start.sh
> > ```
> > #!/bin/bash
> > /app/teldrive run --config $HOME/app/config.toml 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This Worked for me
> 
> Yeah, it did work, my only issue now is for some reason, After i successfullly logged in, im still sent back to the log in screen. let me walk you through
> 
> Step 1: The main login page shows up Step 2: I enter phone number and it requests for code Step 3: I enter code and press login. Step 4: It loaadsss then it goes back to the log in page.
> 
> Nothing showed up on the logs as red flags, hell, the logs say that the login was successful, but on the actual page, its just not doing anything.

You have to enter directly from the link

**Comment by jojogamezHub** [comment]
> > > dockerfile
> > > ```
> > >   FROM ubuntu:latest
> > >   
> > >   RUN apt-get update && \
> > >       apt-get install -y ca-certificates tzdata wget tar curl
> > >   
> > >   WORKDIR /app
> > >   COPY . .
> > >   RUN chmod -R 777 /app 
> > >   
> > > 
> > >   RUN --mount=type=secret,id=gist_teldrive,mode=0444,required=true \
> > >       wget https://github.com/divyam234/teldrive/releases/latest/download/teldrive-1.1.3-linux-amd64.tar.gz -O /app/teldrive.tar.gz && \
> > >       tar xvf /app/teldrive.tar.gz -C /app  && \
> > >       wget $(cat /run/secrets/gist_teldrive) -O /app/config.toml && \
> > >       chmod a+x /app/teldrive && chmod 777 /app/config.toml  && \
> > >       touch /app/session.db && \
> > >       chmod 777 /app/session.db
> > >   
> > >   RUN chmod a+x /app/start.sh
> > >   
> > >   CMD ["./start.sh"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > start.sh
> > > ```
> > > #!/bin/bash
> > > /app/teldrive run --config $HOME/app/config.toml 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This Worked for me
> > 
> > 
> > Yeah, it did work, my only issue now is for some reason, After i successfullly logged in, im still sent back to the log in screen. let me walk you through
> > Step 1: The main login page shows up Step 2: I enter phone number and it requests for code Step 3: I enter code and press login. Step 4: It loaadsss then it goes back to the log in page.
> > Nothing showed up on the logs as red flags, hell, the logs say that the login was successful, but on the actual page, its just not doing anything.
> 
> You have to enter directly from the link

Sorry, if its a dumb question but, may you elaborate on that. Ik its annoying to ask that sort of question, but I had to make sure that i get what you mean.

**Comment by Pe0xonN** [comment]
> > > > dockerfile
> > > > ```
> > > >   FROM ubuntu:latest
> > > >   
> > > >   RUN apt-get update && \
> > > >       apt-get install -y ca-certificates tzdata wget tar curl
> > > >   
> > > >   WORKDIR /app
> > > >   COPY . .
> > > >   RUN chmod -R 777 /app 
> > > >   
> > > > 
> > > >   RUN --mount=type=secret,id=gist_teldrive,mode=0444,required=true \
> > > >       wget https://github.com/divyam234/teldrive/releases/latest/download/teldrive-1.1.3-linux-amd64.tar.gz -O /app/teldrive.tar.gz && \
> > > >       tar xvf /app/teldrive.tar.gz -C /app  && \
> > > >       wget $(cat /run/secrets/gist_teldrive) -O /app/config.toml && \
> > > >       chmod a+x /app/teldrive && chmod 777 /app/config.toml  && \
> > > >       touch /app/session.db && \
> > > >       chmod 777 /app/session.db
> > > >   
> > > >   RUN chmod a+x /app/start.sh
> > > >   
> > > >   CMD ["./start.sh"]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > start.sh
> > > > ```
> > > > #!/bin/bash
> > > > /app/teldrive run --config $HOME/app/config.toml 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This Worked for me
> > > 
> > > 
> > > Yeah, it did work, my only issue now is for some reason, After i successfullly logged in, im still sent back to the log in screen. let me walk you through
> > > Step 1: The main login page shows up Step 2: I enter phone number and it requests for code Step 3: I enter code and press login. Step 4: It loaadsss then it goes back to the log in page.
> > > Nothing showed up on the logs as red flags, hell, the logs say that the login was successful, but on the actual page, its just not doing anything.
> > 
> > 
> > You have to enter directly from the link
> 
> Sorry, if its a dumb question but, may you elaborate on that. Ik its annoying to ask that sort of question, but I had to make sure that i get what you mean.

Do you have a public huggingface project? If you don't, turn it on in the settings and then go to the repository from the link. Do you know how to go to the repository from the link?

**Comment by Pe0xonN** [comment]
@jojogamezHub 
![image](https://github.com/divyam234/teldrive/assets/142345756/4f6166de-8746-491d-9f7e-af2020f1579f)

![image](https://github.com/divyam234/teldrive/assets/142345756/4c5062a9-908f-4337-a77e-8e76f76e2992)

**Comment by jojogamezHub** [comment]
> @jojogamezHub ![image](https://private-user-images.githubusercontent.com/142345756/306752421-4f6166de-8746-491d-9f7e-af2020f1579f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ2NDAsIm5iZiI6MTcwODU0NDM0MCwicGF0aCI6Ii8xNDIzNDU3NTYvMzA2NzUyNDIxLTRmNjE2NmRlLTg3NDYtNDkxZC05ZjdlLWFmMjAyMGYxNTc5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxOTM5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGIyM2JiMmFlMjQ5NTRmNDNlM2E1ZDE0YWY4N2ZkNTkxYWQyMDMwZjNmNzM1YzJhODQ4MTc3NjVlOTE5MjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hwv8FqwZ3T337NdcJRm8SByPCSQnJapO1Y8NYABxj7w)
> 
> ![image](https://private-user-images.githubusercontent.com/142345756/306752495-4c5062a9-908f-4337-a77e-8e76f76e2992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ2NDAsIm5iZiI6MTcwODU0NDM0MCwicGF0aCI6Ii8xNDIzNDU3NTYvMzA2NzUyNDk1LTRjNTA2MmE5LTkwOGYtNDMzNy1hNzdlLThlNzZmNzZlMjk5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxOTM5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTMwMDZiZGVhMjU2Y2FhMWEyMjgyOWYyZjE1YTIyNGJjYTM0NThjNDJlY2JlNmVmZTZmODA4NmJmMjdiMzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RoLjEPSxXwGM2X6o7jrQGJAMq2WK2B-_zAtn9FYXz5E)

I did what u told me to do and i gotta say:
**Thank you, so so much. I've been on this thing for like a day or 2 now.**

**Comment by rHohith** [comment]
I Believe we can close this issue now @Pe0xonN
