### ISSUE TITLE
videos do not stream randomly

### ISSUE THREAD

**Issue by xd003** [divyam234/teldrive#138]
I have noticed quite often that some videos would just not stream from the teldrive web UI
It outputs the following error in logs
```
16/02/2024 12:51 PM  DEBUG  requesting file  {"name": "Can't Lose (2011) - S01E01 - Episode 1 - 1080p [WEBDL][8bit][AVC][AAC 2.0][KO].mkv", "bot": "6362481266", "user": "6362481266", "start": 2419854336, "end": 2419854944, "fileSize": 2419854945}
2024/02/16 12:51:55 http: panic serving 110.226.181.115:20592: runtime error: invalid memory address or nil pointer dereference
goroutine 728736 [running]:
net/http.(*conn).serve.func1()
  net/http/server.go:1898 +0xb0
panic({0x12d1d40?, 0x2901c60?})
  runtime/panic.go:770 +0x124
io.(*LimitedReader).Read(0x40012a79f8, {0x40012b4000?, 0x18?, 0x4000b64008?})
  io/io.go:479 +0x40
io.copyBuffer({0xffff52669820, 0x4000d82200}, {0x1b03200, 0x40012a79f8}, {0x0, 0x0, 0x0})
  io/io.go:429 +0x18c
io.Copy(...)
  io/io.go:388
io.CopyN({0xffff52669820, 0x4000d82200}, {0x0, 0x0}, 0x261)
  io/io.go:364 +0x98
github.com/divyam234/teldrive/pkg/services.(*FileService).GetFileStream(0x400056eb40, 0x4000d82200)
  github.com/divyam234/teldrive/pkg/services/file.go:535 +0x133c
github.com/divyam234/teldrive/pkg/controller.(*Controller).GetFileStream(...)
  github.com/divyam234/teldrive/pkg/controller/file.go:172
github.com/gin-gonic/gin.(*Context).Next(0x4000d82200)
  github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x3c
github.com/divyam234/teldrive/cmd.initApp.GinzapWithConfig.func3(0x4000d82200)
  github.com/gin-contrib/zap@v0.2.0/zap.go:59 +0x88
github.com/gin-gonic/gin.(*Context).Next(...)
  github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x40001b9a00, 0x4000d82200)
  github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x514
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x40001b9a00, {0x1b13ff8, 0x40000c2380}, 0x400052f0e0)
  github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x174
net/http.serverHandler.ServeHTTP({0x40014e3e90?}, {0x1b13ff8?, 0x40000c2380?}, 0x6?)
  net/http/server.go:3137 +0xbc
net/http.(*conn).serve(0x40014d7680, {0x1b16c08, 0x40004f0270})
  net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 35
  net/http/server.go:3285 +0x3f0
```

I am pretty sure that its not really a problem with video file since this issue doesn't persist if i restart the teldrive docker. I am not able to narrow down what's causing this issue in first place

Teldrive v1.1.13 ( latest )
rclone v1.65.4

**Comment by DevRush94** [comment]
+1 
Facing the same

**Comment by PotatoPTT** [comment]
+1 
Happens in rclone too

**Comment by xd003** [comment]
I can confirm after some extensive testing that i no longer face this issue when disable-stream-bots is set to false

**Comment by aniel300** [comment]
> I can confirm after some extensive testing that i no longer face this issue when disable-stream-bots is set to false

where can i set this flag/ variable?

**Comment by xd003** [comment]
Reopening this issue as it happens irrespective of whether i keep disable-stream-bots to true or false

**Comment by aniel300** [comment]
> Reopening this issue as it happens irrespective of whether i keep disable-stream-bots to true or false

are u using union with rclone?

**Comment by xd003** [comment]
> > Reopening this issue as it happens irrespective of whether i keep disable-stream-bots to true or false
> 
> are u using union with rclone?

Not rclone union i am using mergerfs, i don't think this matters tho cus i ak streaming from the teldrive remote only

**Comment by aniel300** [comment]
mergerfs can also be sue to merge mounts, are u combining more than one mount and are the crypted?

**Comment by xd003** [comment]
Just merging a local folder & teldrive remote, i am not using encryption atm

**Comment by aniel300** [comment]
umm ok, i have a similar issue but i will confirm if it was a end user error in the next few days

**Comment by xd003** [comment]
i haven't faced this issue recently so closing this
