### ISSUE TITLE
[feature request] File preview

### ISSUE THREAD

**Issue by SkySlider** [divyam234/teldrive#139]
Currently uploaded files don't have any previews, it would be a nice thing to have, especially for photos.

**Comment by Linden10** [comment]
By File previews...you mean like this?
![image_2024-02-19_015705196](https://github.com/divyam234/teldrive/assets/20895359/47c3aa51-d40d-48b5-8d29-f794fb176554)

And/Or this?
![image_2024-02-19_015733559](https://github.com/divyam234/teldrive/assets/20895359/a8561b78-3abd-4a14-ae9b-0ca56db95d1d)

**Comment by Pe0xonN** [comment]
> Currently uploaded files don't have any previews, it would be a nice thing to have, especially for photos.

![image](https://github.com/divyam234/teldrive/assets/142345756/736c6476-4231-48dc-b553-bbe65d0637e3)

This is already implemented into TelDrive

**Comment by SkySlider** [comment]
> > Currently uploaded files don't have any previews, it would be a nice thing to have, especially for photos.
> 
> ![image](https://private-user-images.githubusercontent.com/142345756/306440563-736c6476-4231-48dc-b553-bbe65d0637e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDQzMDYsIm5iZiI6MTcwODUwNDAwNiwicGF0aCI6Ii8xNDIzNDU3NTYvMzA2NDQwNTYzLTczNmM2NDc2LTQyMzEtNDhkYy1iNTUzLWJiZTY1ZDA2MzdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwODI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjY1ZGFhZGYyM2E2NzE3OTUzMmZlYThiNzFhNGMyNTI4ZDE5M2ZjMzllYTdlMDM1MjA4NjBlMGQ2OGE5NGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b8yxs39nrqWsT8zZuh0XtN6JWxuaHboWhGX-rtHCcmo)
> 
> This is already implemented into TelDrive

For some reason, all my previews are just blank grey. I'll try to figure it out.

**Comment by Linden10** [comment]
Make sure you update teldrive to the newest version if you haven’t and switch to grid view. Otherwise I’m not sure why it won’t be showing up as a thumbnail…

Are the images in jpg, png, gif or is it something else? Those three should show a thumbnail.

Oh and only images show thumbnails btw, video files don’t show thumbnails on teldrive.

**Comment by Pe0xonN** [comment]
> > > Currently uploaded files don't have any previews, it would be a nice thing to have, especially for photos.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/142345756/306440563-736c6476-4231-48dc-b553-bbe65d0637e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDQzMDYsIm5iZiI6MTcwODUwNDAwNiwicGF0aCI6Ii8xNDIzNDU3NTYvMzA2NDQwNTYzLTczNmM2NDc2LTQyMzEtNDhkYy1iNTUzLWJiZTY1ZDA2MzdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwODI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjY1ZGFhZGYyM2E2NzE3OTUzMmZlYThiNzFhNGMyNTI4ZDE5M2ZjMzllYTdlMDM1MjA4NjBlMGQ2OGE5NGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b8yxs39nrqWsT8zZuh0XtN6JWxuaHboWhGX-rtHCcmo)
> > This is already implemented into TelDrive
> 
> For some reason, all my previews are just blank grey. I'll try to figure it out.

And you can download files
