### ISSUE TITLE
Can't login with 2FA enabled

### ISSUE THREAD

**Issue by rolsoft** [divyam234/teldrive#14]
I'm using docker, I can't login to teldrive with phone number or QR code, I have 2FA enabled on telegram (I suppose it is that, because it doesn't prompt me for my password at login).

After trying to login on the teldrive web interface I receive a telegram official message that says "Incomplete login attempt at..."

**Comment by divyam234** [comment]
@rolsoft  I don't have 2FA  enabled that why  it was not implemented let me I am to able to itegrate with current login

**Comment by divyam234** [comment]
@rolsoft  2FA support is added check now

**Comment by rolsoft** [comment]
It works! Thank you so much
