### ISSUE TITLE
Adding Bots Issue

### ISSUE THREAD

**Issue by rHohith** [divyam234/teldrive#152]
I logged in  teldrive and while adding bots the error i encountered is 
![teldrive](https://github.com/divyam234/teldrive/assets/31046649/cd37e1a0-63db-48c0-8f74-1079d1f6f985)
`FRESH_CHANGE_ADMINS_FORBIDDEN`

In teldrive logs

`26/02/2024 02:48 PM	ERROR	error{error 26 0  retry middleware skip: rpcDoRequest: rpc error code 406: FRESH_CHANGE_ADMINS_FORBIDDEN}`
`26/02/2024 02:48 PM	ERROR	callback: retry middleware skip: rpcDoRequest: rpc error code 406: FRESH_CHANGE_ADMINS_FORBIDDEN`

**Comment by azeyrx** [comment]
Read the README.md file...

It says that you should wait some time (20 - 30 min) before adding bots.

**Comment by truongbber** [comment]
does adding bots increase download speed, or what is the purpose of adding more bots, can't find any tutorial related to this

**Comment by hitokirihahn** [comment]
> does adding bots increase download speed, or what is the purpose of adding more bots, can't find any tutorial related to this

this is what i'm curious too, what is the function of bots added?
