### ISSUE TITLE
Docker hub image

### ISSUE THREAD

**Issue by musahi0128** [divyam234/teldrive#18]
Hi, if you could make this available on Docker Hub I think it will be much more easier for a noob like me to run it. Please consider. Thanks!

**Comment by musahi0128** [comment]
Would you tell me the docket hub address?

**Comment by divyam234** [comment]
@musahi0128  Why you wanna use dockerhub when images are already being published on github

**Comment by musahi0128** [comment]
I'm new to docker and I find running image from Docker hub is much more convinient and to my experience it is less of a headache.

**Comment by divyam234** [comment]
@musahi0128  Can you explain how docker hub is convinient  as you have to docker pull there also .I am assuming that  you are new  to programming otherwise you shouldn't have ask such question

**Comment by musahi0128** [comment]
Yes I am new to all this stuff, I find downloading the repo is more involving while running from docker hub image is just one line command to get the stuff running.

**Comment by divyam234** [comment]
@musahi0128  github has its own dockerhub like registry which is far better than dockerhub and all the images are published there https://github.com/divyam234/teldrive/pkgs/container/teldrive%2Fserver so publishing to docker hub is useless

**Comment by musahi0128** [comment]
Wow I didn't know that was exist. Thank you. It will be cool if you mention that when closing the issue instead of closing without any explanation or reply.
