### ISSUE TITLE
Getting ERROR: function gen_random_bytes(integer) does not exist (SQLSTATE 42883

### ISSUE THREAD

**Issue by vavtnen** [divyam234/teldrive#181]
I imported postgresql data from Neon.tech to local server, but I get this error whenever I tried to upload a file

28/03/2024 03:43 AM     ERROR   &{ERROR: function gen_random_bytes(integer) does not exist (SQLSTATE 42883) 0}
28/03/2024 03:43 AM     ERROR   ERROR: function gen_random_bytes(integer) does not exist (SQLSTATE 42883)
28/03/2024 03:43 AM     INFO            {"status": 500, "method": "POST", "path": "/api/files", "query": "", "ip": "removed", "user-agent": "rclone/v1.66.1", "latency": 0.989749415, "time": "2024-03-28T03:43:40Z"}

Download is working fine. Any suggestion?

Thanks

**Comment by azeyrx** [comment]
You need to load the pgcrypto extension in the current database/schema with

```CREATE EXTENSION pgcrypto;```


It is best if you first initialize teldrive locally with the database and then insert the data.

**Comment by fakhriyf** [comment]
very usefull. hello i'm from indonesia
