### ISSUE TITLE
unable to access discord server

### ISSUE THREAD

**Issue by WilderDrone** [divyam234/teldrive#189]
hi

i am having issues setting up teldrive. i posted about it on the discord server but few hours later when i checked for a reply to my post i found the channel missing, tried to add it again but it says "unable to accept invite". it has been like that for a while. tried from another discord account and it is the same.

also i am unable to go beyond the initial setup of teldrive as the docker keeps restarting. the logs only say - "No log line matching the '' filter". 

what could be the issues?

TIA

**Comment by aniel300** [comment]
u probably were banned for posting ur issue there same thing happened to me. a bunch of clown running that discord over there.

**Comment by divyam234** [comment]
@aniel300  Really I am not active on discord that much maybe moderator have had kicked some people  I will revoke all bans and limit moderator permissions.

**Comment by aniel300** [comment]
> @aniel300  Really I am not active on discord that much maybe moderator have had kicked some people  I will revoke all bans and limit moderator permissions.

yeah bro i all i did was shared my issues, maybe like twice and i was banned in my opinion for no reason but am glad u are taking matters into your hands 🙏

**Comment by aniel300** [comment]
> @aniel300 Really I am not active on discord that much maybe moderator have had kicked some people I will revoke all bans and limit moderator permissions.

what is the discord invite?

**Comment by r0gu3ptm** [comment]
Same thing happened to me, i was out for some time and cannot rejoin, am I banned ?
