### ISSUE TITLE
It should be like this

### ISSUE THREAD

**Issue by PLoliwi** [divyam234/teldrive#195]
![image](https://github.com/divyam234/teldrive/assets/95148122/efdb52d4-057c-4e47-be0a-191c6791bf95)

It should be | Music | Movies | because is it just that or was it like that?

**Comment by PLoliwi** [comment]
![image](https://github.com/divyam234/teldrive/assets/95148122/3cce5454-72ea-42ec-8b3d-31c8c7362a04)

**Comment by PLoliwi** [comment]
![image](https://github.com/divyam234/teldrive/assets/95148122/91e571be-760b-42cb-851a-d97ae862fcb1)

![image](https://github.com/divyam234/teldrive/assets/95148122/650ddf81-3ecd-4838-a8dc-d7b9706b1728)

**Comment by PLoliwi** [comment]
Video !?

**Comment by Pe0xonN** [comment]
@divyam234

**Comment by PLoliwi** [comment]
@divyam234  can you help me with it or fix it

**Comment by PLoliwi** [comment]
FIX GOOD
