### ISSUE TITLE
When viewing images with a filename format like "p1.png, p20.png, p300.png, etc", images get skipped over...

### ISSUE THREAD

**Issue by Linden10** [divyam234/teldrive#196]
Hmm...I have an bug I've been noticing since using teldrive back in December. I thought the issue would resolve itself in time but...
I might as well report it after it's been bothering me for a while.

When filenames are named like the image below:
![image](https://github.com/divyam234/teldrive/assets/20895359/8cbbff5a-b506-4bd9-9f04-3be96032281a)

Even if the images appear in order in the ui, when viewing...let's say "p0.jpg" and clicking on the arrow to view the next image, the expected behavior is it should load "p1.jpg" but instead it skips over to "p10.jpg" like in the video below.

https://github.com/divyam234/teldrive/assets/20895359/b09aaf11-5342-4f43-9ae3-e2ae3d7b06b3

This applies to any filename that starts with "p#" even if they're extra characters in the filename "p#_xxxxxxx.png".
Sorry for not reporting this issue soon and I hope there's a way to fix this strange bug.

**Comment by divyam234** [comment]
Numeric ordering is  not handled in previews while in file compoents its uses it by default  I will add it in next release its a minimal change in ui
