### ISSUE TITLE
login error - using docker version

### ISSUE THREAD

**Issue by saqebakhter** [divyam234/teldrive#2]
When i try to run it using the docker version -- i get an error after i try to login on the http://ip:8000 page : 

```
nginx      | 192.168.20.71 - - [17/Aug/2023:14:27:51 +0000] "POST /api/auth/login HTTP/1.1" 500 43 "http://192.168.20.65:8000/login?from=%2Fmy-drive" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" "-"
server     | [GIN] 2023/08/17 - 14:29:18 | 500 |   20.042748ms |   192.168.20.71 | POST     "/api/auth/login"
server     | Error #01: failed to create or update user
```

**Comment by dceldran** [comment]
Hi! yeah i already have the same error, the problem is into postgresql because the field user_id is out of range.

I can solve the issue with `ALTER TABLE teldrive.users ALTER COLUMN user_id TYPE BIGINT;`

**Comment by divyam234** [comment]
I have updated the data type to bigint .Originally I had set it to bigint only might have  chnaged  when I copied  it from pgadmin to migrations.

**Comment by saqebakhter** [comment]
Thanks this is fixed with latest build
