### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by devcrono** [divyam234/teldrive#20]
@divyam234 Your project is wonderful, and I'm really enjoying testing it, but I'm sending you some suggestions to improve your application even more.

1 - Would you be able to implement the function so that when you upload a photo or video, it already generates a thumbnail on the channel?
2 - simple http direct links, using telegram servers for download
3 - share a folder or file, leaving it public (open to everyone who has the link) or to the recipient's @do telegram
example: I share folder A only for you @you have access and will see it in the list of shared folders
4 - upload in drag and drop
5 - fix the options menu that appears when clicking with the right mouse button in firefox and other browsers, because the options only appear in CHROME.
it would be cool if you put all the options in the gear options or a new button next to the gear
6 - support multi channels for upload
7 - translation into other languages (in my case Brazilian Portuguese)

**Comment by joseavilasg09** [comment]
@devcrono @divyam234 The translation feature would be good. I can help with spanish translation.
