### ISSUE TITLE
Unable to use rclone copy or sync with teldrive backend {Detailed logs added}

### ISSUE THREAD

**Issue by bolavefasfas** [divyam234/teldrive#200]
I'm experiencing an issue with the teldrive backend in rclone. While I can successfully use `rclone tree`, `ls`, and `lsd` commands to view files uploaded from the WebUI, I'm unable to use `rclone copy` or `sync` commands to upload files to Telegram.

**Error Message:**

When running `rclone copy "rclone.1" "tele:" -vvPP`, I receive the following error:
```
HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: no channels found\"}"
```
The file size of the upload keeps increasing, but the upload itself fails.

### rclone tree
```
rclone tree tele:
/
└── Software
    └── rclone-v1.66.2-windows-amd64.zip
```    

### rclone copy Error

```
rclone copy "rclone.1" "tele:" -vvPP
2024/04/22 11:57:27 DEBUG : rclone: Version "v1.66.2" starting with parameters ["rclone" "copy" "rclone.1" "tele:" "-vvPP"]
2024/04/22 11:57:27 DEBUG : Creating backend with remote "rclone.1"
2024/04/22 11:57:27 DEBUG : Using config file from "C:\\Users\\W11\\AppData\\Roaming\\rclone\\rclone.conf"
2024/04/22 11:57:27 DEBUG : fs cache: adding new entry for parent of "rclone.1", "//?/C:/Users/W11/Downloads/rclone-v1.66.2-windows-amd64/rclone-v1.66.2-windows-amd64"
2024/04/22 11:57:27 DEBUG : Creating backend with remote "tele:"
2024/04/22 11:57:28 DEBUG : Saving config "access_token" in section "tele" of the config file
2024/04/22 11:57:28 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2024/04/22 11:57:29 DEBUG : rclone.1: Need to transfer - File not found at Destination
2024/04/22 11:57:30 DEBUG : pacer: low level retry 1/10 (error HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: no channels found\"}")
2024/04/22 11:57:30 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2024/04/22 11:57:31 DEBUG : pacer: low level retry 2/10 (error HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: no channels found\"}")
2024/04/22 11:57:31 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2024/04/22 11:57:32 DEBUG : pacer: low level retry 3/10 (error HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: no channels found\"}")
2024/04/22 11:57:32 DEBUG : pacer: Rate limited, increasing sleep to 80ms
Transferred:          732 KiB / 2.397 MiB, 30%, 211.982 KiB/s, ETA 8s
Transferred:            0 / 1, 0%
Elapsed time:         5.0s
Transferring:
 *                                      rclone.1: 29% /2.397Mi, 211.949Ki/s, 8s^C
```   
    
**Rclone Config:**

My rclone config is as follows:
```
[tele]
type = teldrive
access_token = redacted
api_host = http://localhost:8080
channel_id = -100redacted
```
I have added the channel in the WebUI, and it's showing files in both the WebUI and rclone. However, I'm unable to copy or upload files to Telegram using rclone.

**Steps to Reproduce:**

1. Add a channel in the WebUI.
2. Configure rclone with the Telegrive backend.
3. Run `rclone copy` or `sync` command to upload a file to Telegram.

**Expected Behavior:**

The file should be successfully uploaded to Telegram.

**Actual Behavior:**

The upload fails with an HTTP error 500, and the file size keeps increasing.

**Comment by divyam234** [comment]
@bolavefasfas  remove -100 from start  or set default channel from UI settings

**Comment by bolavefasfas** [comment]
Worked Thanks.
I've successfully deployed Teledrive and created a folder and upload a file. However, when I redeployed Teledrive on a fresh VPS with the same account and channel, the old files did not show up in the same channel. (The old files were still present in the channel.
Can someone explain why the files are not persisting across deployments? Is there a configuration or setting I'm missing?

I guess I changes the vps so new postgress so old database not their thats why right ?

And please can you send a ideal rclone config for uploading decent amount of data ?
