### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by Xabiman** [divyam234/teldrive#206]
I'm using Teldrive and Rclone in a Feral Hosting VPS but support of Feral close continuously (after 2 or 3 days using it) my slot because they say Teldrive  is consuming a lot of CPU usage and that's not allowed.
Do you know how to decrease CPU usage of Teldrive?

**Comment by divyam234** [comment]
Cpu usage totally depends on you configuration one upload is using 16 concurrent threads for uploading  so if you are uplaoding large no of files concurrently cpu usage will sky rocket , so decrease  concurrent uploads in rclone.

**Comment by Xabiman** [comment]
Thank you very much @divyam234 . I've adjusted the rclone command and now it seems to have lower CPU usage.
