### ISSUE TITLE
For the life of me I cant get thumbnails working.  Please see my logs..

### ISSUE THREAD

**Issue by bpawnzZ** [divyam234/teldrive#213]
Hello all.  Teldrive is an amazing project and i love the fact I can use Telegam as my cloud and have everything working perfectly with one small exception.  I am running the image-resizer in an adjacent container and no matter how I work my networking I cannot get thumbnails working reliably.  Is there other option for a thumbnails that could work. I briefly had it working yesterday but it stopped again.  In my logs i have a code 500 error(see screenshot below).  Can you give me any suggestions to fix this or another option??  Thank you

![Screenshot_20240501_215956](https://github.com/divyam234/teldrive/assets/151177455/25e51911-bbf7-4745-a84d-919dca4d33d6)

i am very technical and its rare for me to have an issue like this.  Im almost of the opinion that image-resizer is the problem and not me. Lol.. Please tell me where I am going wrong. Or is there an environmental variable related to image-resizer I am unaware of in order to get it working consistently??

**Comment by joseavilasg** [comment]
Your resizer server can't reach the localhost address of your teldrive instance since they are different containers.

**Comment by bpawnzZ** [comment]
> Your resizer server can't reach the localhost address of your teldrive instance since they are different containers.

Yes they are different containers but I have manually put them onto the same network and they still don't play together correctly.  For instance opening portainer and making sure both are on the same network and then saying for teldrive to connect to image resizer via ip or hostname i assigned does not work.  I even jumped into the shell of teldrive, installed telnet and 'telnet image_resizer_instance ip' and it connects, it can obviously see it. But still teldrive and image-resizer dont work this way.  Which i don't understand why this is an issue. Hope I explained well enough.  Feel free to ask if you have any other questions.

However I was able to make it work but it is not optimal.  What i did was I have teldrive deployed in my cloud/server and then am running image-resizer locally.  I set it to look at localhost and it actually works.  But this is not optimal.  meaning every machine i want to access my teldrive on would need to have a image-resizer running in docker.  Why cant two containers on the same docker network communicate and handle image resizing.  This for a fact does not work and how I would optimally like to have everything setup.

**Comment by joseavilasg** [comment]
If you have a cloud server, you could just expose both services on different ports and use them like that. For example, if your server's IP is `143.48.216.182`, your teldrive could be running on `143.48.216.182:8888` and the resizer on `143.48.216.182:7777`. Then, just use `143.48.216.182:7777` as the resizer host in teldrive settings.

**Comment by bpawnzZ** [comment]
> If you have a cloud server, you could just expose both services on different ports and use them like that. For example, if your server's IP is `143.48.216.182`, your teldrive could be running on `143.48.216.182:8888` and the resizer on `143.48.216.182:7777`. Then, just use `143.48.216.182:7777` as the resizer host in teldrive settings.

The issue with what you described above is it would require two open ports. I tried something similar which required one open port but nonethless didn't work. What i did was I have the service sitting behind NGINX and routing to 'teldrive.example.com'.  Then i had the service listening at 'ip_address:open_port'.  For reasons unknown this would not connect.  I'm assuming reverse proxy had something to do with it.  However websockets is enabled and should have handled that.

What i would like to do is; assume i assigned the hostname 'teldrive' to teldrive and hostname 'resizer' to image_resizer.  And both are the internal docker network 172.18.0.0/16.  Why isnt it possible for me to set the image_resizer URL as http://resizer:7860 is the internal port i believe without the port forward and be able to connect like that.  Not exposing any extra ports and keeping that routing internal.  Nginx is handing serving the teldrive instance to my subdomain. I know the services can see eachother and they should be able to communicate.  As i said above before from inside teldrive i can connect to image_resizer with telnet.  I just don't get why they cannot, and they cant.  Like does teldrive only allow a connection on localhost to the image_resizer??  Because that is almost what it appears to be to me.

**Comment by divyam234** [comment]
@bpawnzZ  use local network in docker compose for teldrive and resize service

**Comment by Pe0xonN** [comment]
This can be done somehow without docker desktop on Windows

**Comment by bpawnzZ** [comment]
> use local network

I don't understand how this will solve my routing problems. I mean i do have the machine ported through to the local network.  However it appears as though unless the host is specifically 'localhost:assigned_port' it will not connect.  Which can't work like that in a cloud setup. Can you please elaborate on what you mean??  Maybe I'm misunderstanding you.  Thank you

**Comment by bpawnzZ** [comment]
> This can be done somehow without docker desktop on Windows

I'm using arch linux on both my workstation/laptop and server currently.  But I think what you are referring to is [teldrive-ui](https://github.com/divyam234/teldrive-ui).  You can easily build this UI with yarn and deploy that way.  However that wont solve my issues with image-resizer. I've tried. Lol

**Comment by Pe0xonN** [comment]
> > This can be done somehow without docker desktop on Windows
> 
> I'm using arch linux on both my workstation/laptop and server currently. But I think what you are referring to is [teldrive-ui](https://github.com/divyam234/teldrive-ui). You can easily build this UI with yarn/node/js and deploy that way. However that wont solve my issues with image-resizer. I've tried. Lol

I mean the image resizer

**Comment by divyam234** [comment]
@bpawnzZ If you are have personal domain use caddy instead of nginx this will allow to use wildcard domains teldrive.example.com and resize.example.com  on same server .

**Comment by bpawnzZ** [comment]
> > > This can be done somehow without docker desktop on Windows
> > 
> > 
> > I'm using arch linux on both my workstation/laptop and server currently. But I think what you are referring to is [teldrive-ui](https://github.com/divyam234/teldrive-ui). You can easily build this UI with yarn/node/js and deploy that way. However that wont solve my issues with image-resizer. I've tried. Lol
> 
> I mean the image resizer

If you can find the source for image-resizer I would be much appreciative.  I cant find it. Only the docker images.  If I could find that I'm pretty sure I could solve my own problem.

**Comment by bpawnzZ** [comment]
> @bpawnzZ If you are have personal domain use caddy instead of nginx this will allow to use wildcard domains teldrive.example.com and resize.example.com on same server instead of using diff ports expose both service through caddy config.

That is exactly how I am setup on Nginx.  I put resizer on resizer.example.com and i got error 500 codes inside the logs.  That was deff one of the multiple configs i setup.  but when i set it to to https://resizer.example.com:443 inside teldrive it did try to connect, but gave me error 500.  fyi without including the 443 i got nothing back in logs.

i guess i just don't know what caddy offers that nginx doesn't.  Wildcard domains couldn't be any simpler or straightforward to setup in NGINX.  Unless you are saying you are aware of some specific issue regarding NGINX

**Comment by joseavilasg** [comment]
@bpawnzZ Could you share your nginx config? As you said, it should work, but I'm aware that nginx can sometimes cause issues with teldrive.

**Comment by bpawnzZ** [comment]
> @bpawnzZ Could you share your nginx config? As you said, it should work, but I'm aware that nginx can sometimes cause issues with teldrive.

I actually just swapped over to Caddy as suggested by someone here. It did NOT solve my problem but I do kinda like it.  I get Error 500 continuously if I try to make it resolve to anything except localhost.  The format of my Caddyfile is below. Super simple.. Let me know if you want me to provide anything else.  And sorry for just getting back to you.

````
{
    email bpawnzZ@example.xyz
}

teldrive.example.xyz {
    reverse_proxy http://teldrive:8080
}

resizer.example.xyz {
    reverse_proxy http://example:7860
}
...................
````
![Screenshot_20240504_110529](https://github.com/divyam234/teldrive/assets/151177455/20688599-c460-4087-82a5-6f9367449105)

**Comment by joseavilasg** [comment]
@bpawnzZ Actually never used Caddy before. It should not be hard though. Have you tested with another image, from google for example? Do you get the same error?

**Comment by 2379** [comment]
Thumbnails worked for me then I wrote "http://" as a resizer host and skiped compression entirely
Works at least as a termorary solution

**Comment by Linden10** [comment]
> Thumbnails worked for me then I wrote "http://" as a resizer host and skiped compression entirely Works at least as a termorary solution

Wait REALLY?! Thank you thank you, this works great without the need of having a resizer host when viewing thumbnails! I didn't know this until your comment, nice to finally see thumbnails without compression again heh.

**Comment by bpawnzZ** [comment]
> Thumbnails worked for me then I wrote "http://" as a resizer host and skiped compression entirely
> Works at least as a termorary solution

I am able to get resizer working if it is running on my local machine but not the host where Teldrive is actually hosted. Are you saying that I could have resizer running on the same hosts at where Teldrive is located?? Just trying to understand you a little more clearly
