### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by v1peeer** [divyam234/teldrive#218]
I'm hosing teldrive locally on my pc. There aren't any errors in the log but I'm stuck on the "Please Wait...":
![image](https://github.com/divyam234/teldrive/assets/107548344/fe7064df-a9a1-459a-b683-03774e5e5afa)
![image](https://github.com/divyam234/teldrive/assets/107548344/e4cff3e9-ee92-4d4a-a45d-614cabf9e57f)

**Comment by v1peeer** [comment]
Okay so what I just did was running teldrive on linux. There it atleast shows an error message:
![image](https://github.com/divyam234/teldrive/assets/107548344/4171198d-5c0f-4a68-9b45-50590c0be2ba)

**Comment by dongxiat** [comment]
> Okay so what I just did was run teldrive on linux. There it atleast shows an error message: ![image](https://private-user-images.githubusercontent.com/107548344/328206527-4171198d-5c0f-4a68-9b45-50590c0be2ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDQwNzgsIm5iZiI6MTcxODkwMzc3OCwicGF0aCI6Ii8xMDc1NDgzNDQvMzI4MjA2NTI3LTQxNzExOThkLTVjMGYtNGE2OC05YjQ1LTUwNTkwYzBiZTJiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxNzE2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjUwMTkyZTk1YzcyNTI2ZTJmZWFmMDY3Yjg5Y2YzZGU5ZjU2N2YzZTI1Njk3YzExMTRjMTQ1YWM4ODg1NDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-pk6tqaDSjTnWPZj9EFpJbgva8pKo0nhb80EWbTYFj0)
> 
> edit: the hash i entered was wrong, i'll just run teldrive on my raspberry with linux (windows still doesn't work).

yep i just run on windows its stuck Please Wait.. forever

**Comment by akang943578** [comment]
Why closed? I'm also this issue. I run with docker-compose in my ubuntu as server, can login by web browser on Mac, but can not by web browser on my Android.
