### ISSUE TITLE
Rclone IO error when using teldrive

### ISSUE THREAD

**Issue by rolsoft** [divyam234/teldrive#22]
I built your [fork of rclone](https://github.com/divyam234/rclone) and used the binary compiled to add the teldrive type, I obtained the "access_token" by getting the cookies from teldrive webui like this:
![cookie "user-session" from the teldrive web ui when logged in](https://github.com/divyam234/teldrive/assets/127045317/e70e52a5-83cf-4b76-bf16-f0bf2060bb3e)
And copying the full user-session value.

### On rclone when creating the remote:
I entered as the api host `http://localhost:8000`, as any other port gave a connection denied error, so I suppose it goes through the haproxy.

But when I try to mount the remote and use it I get this error on rclone `IO error: invalid character '<' looking for beginning of value`.

And I get a `'.': Input/output error` when trying to ls on the directory.

Am I using the correct values? Is your rclone fork currently working?

Thank you for the project

**Comment by divyam234** [comment]
@rolsoft add /api in the end

**Comment by rolsoft** [comment]
It's working, thank you so much
