### ISSUE TITLE
Stuck on uploading 20+ pdf books

### ISSUE THREAD

**Issue by fireinrain** [divyam234/teldrive#227]
Hi, thanks for your works.
Recently i use teldrive to upload 20+ pdf books to tg channel, and it stuck when upload 4 books successfully.
Here is the network monitor of chrome dev tool:
<img width="1489" alt="image" src="https://github.com/divyam234/teldrive/assets/14249262/eeb9af38-990a-4e76-81f4-73387be8a9e3">

I dont know why, my network is fine.

does this may be a bug?

**Comment by fireinrain** [comment]
I have change my dev tool to no throttling

<img width="1505" alt="image" src="https://github.com/divyam234/teldrive/assets/14249262/96718922-327f-4278-845a-657e1755264a">

it still happens stuck on uploding...

i can sure this may be a bug.

**Comment by divyam234** [comment]
Did you see any error on console btw you can use rclone which is  preferred way of uplaoding  files

**Comment by fireinrain** [comment]
> Did you see any error on console btw you can use rclone which is preferred way of uploading files

I dont see any error on console, and i have test the case with many small pdf, it success, but with many large pdf, such as
150MB pdf, it will be stuck while uploading.

**Comment by fireinrain** [comment]
> > Did you see any error on console btw you can use rclone which is preferred way of uploading files
> 
> I dont see any error on console, and i have test the case with many small pdf, it success, but with many large pdf, such as 150MB pdf, it will be stuck while uploading.

Here is the pic of stuck uploading:
<img width="1566" alt="image" src="https://github.com/divyam234/teldrive/assets/14249262/f6da621e-ff0c-4f4f-b52a-e03467de7de1">

it tells me pay load too large,  i want to know how to fix this. and you say i can use rclone for uploading files,  as far as i know,
rclone need drive support webdav, does teledrive support webdav?  hope you can reply, thanks very much.

**Comment by divyam234** [comment]
@fireinrain  teldrive has native rclone support  read docs carefully also  the error  you  jave shown is not  of teldrive rather its your own misconfiguration you are using clouflare dns which limits upload size to 100MB one way to fix this is to turn off dns proxy in clouflare dashboard.

**Comment by fireinrain** [comment]
> clouflare

thanks very much divyam234.
