### ISSUE TITLE
Register already uploaded files

### ISSUE THREAD

**Issue by musahi0128** [divyam234/teldrive#23]
Hi, I have been uploading tons of files directly to a channel via Telegram bot api running locally. Is there any way I can add those files so it will appear and accessible from this apps? I was looking on the database and I think that should be possible. Thanks!

**Comment by divyam234** [comment]
Not possible in current implmentation  you can fork repo and modify accordingly

**Comment by CakesTwix** [comment]
@divyam234, even if me manually specify the file ID and write to the DT via UI?
