### ISSUE TITLE
Rclone upload

### ISSUE THREAD

**Issue by jferdom** [divyam234/teldrive#236]
I´ve mounted teldrive and everything appears to work ok via web.

I configured rclone, mount a unit in windows, and for read files, it works ok. However, I can´t copy files to the mounted unit.

![imagen](https://github.com/divyam234/teldrive/assets/171198381/7d6a330f-b52b-4b29-be97-e724643be853)

It returns to me an error 500.

This is my rclone.conf:

![imagen](https://github.com/divyam234/teldrive/assets/171198381/7f01c5cb-4db5-4145-822f-f0922aaf9a59)

This is the console of teldrive...

![imagen](https://github.com/divyam234/teldrive/assets/171198381/f4015d01-9165-4800-9a67-0d1cef48c17e)

Any ideas?

**Comment by Linden10** [comment]
Hmm...I noticed this error in that log:
"callback: no channels found"

Have you configured your channels for your files to be uploaded to?
Open teldrive on your browser, check your settings (Your profile picture) and under Account, make sure to select the channel on your telegram account where you plan to upload files to.

Hope this helps!

**Comment by jferdom** [comment]
Yes, I do. In fact, I can upload files without problem with the Teldrive web interface. 

Also, I can read/download files from the rclone mounted unit without problems. 

My problem is I can´t upload files with rclone. Neither mounting the unit or using rclone copy...

**Comment by 1eeMY** [comment]
Make sure to set up the channel in the web interface and then delete the ‘channel_id’ from the rclone configuration.

**Comment by jferdom** [comment]
It worked!!. Thank you!!
