### ISSUE TITLE
huggingface.co It works on 1.3.0 and does not work on 1.3.1.

### ISSUE THREAD

**Issue by Pe0xonN** [divyam234/teldrive#243]
Is it possible to fix this somehow?

**Comment by Pe0xonN** [comment]
![image](https://github.com/divyam234/teldrive/assets/142345756/945c3696-2112-4017-b7e4-d7d133af2fa3)

**Comment by Linden10** [comment]
Ah I notice that 1.3.1 of teldrive (running on windows, not on huggingface like you) is also unable to run as it immediately closes. So I reverted back to 1.3.0 for the moment. Yup!

**Comment by xd003** [comment]
It has nothing to do with huggingface. 1.3.1 is broken for everyone, use 1.3.0

**Comment by Pe0xonN** [comment]
> It has nothing to do with huggingface. 1.3.1 is broken for everyone, use 1.3.0

I wonder if this will be fixed?

**Comment by xd003** [comment]
Ofcourse, as soon as the dev notices it

**Comment by xd003** [comment]
This issue is now fixed, should be closed
