### ISSUE TITLE
Rclone continuously opens ports when uploading and never closes them, causing huge errors!

### ISSUE THREAD

**Issue by Linden10** [divyam234/teldrive#245]
This is a huge bug I just discovered that I'm not sure if anyone would notice if not uploading files that are over 5K or above.
It's a problem I believe affects everyone using the newest versions of rclone (unkown how long it's existed though).

Teldrive: 1.3.1 (Latest)
Rclone: v1.66.3 (Latest)
OS: Windows 10 (Latest)

So...I noticed that whenever I'm uploading a ton of files (Over 5K, size doesn't matter), rclone will eventually stop and throw this error:

> `2024/06/01 09:49:23 ERROR : www/img/pictures/General_Hikari/A_Hikari_ranked0_etc1_0001.rpgmvp: Failed to copy: HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"start: dial failed: dial tcp IPADDRESS:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.; dial tcp IPADDRESS:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.; dial tcp IPADDRESS:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.\"}"`

This is because Rclone, when uploading files, continuously creates and uses ports but never closes them!
![Recording2024-06-01at13 33 30-ezgif com-censor](https://github.com/divyam234/teldrive/assets/20895359/45c4b8e0-5ec5-477e-a1bf-f1940d7f1efe)
*Added Black Censor Bars to censor my local IP.*

As you can see in the image, rclone is currently uploading and as it begins uploading a new file, a new connection with a different port is made but non of the older connections are ever dropped (even when a file finishes uploading), only until rclone finishes uploading all files or you forcibly close rclone itself (Ctrl+C).

It's because of this that I have to constantly restart rclone because it exhausts all the open ports after uploading over 5K files, that and it affects all programs on the computer as it slows them down and either crash or freeze them due to all the ports being used it and not closed!

This a big bug that wastes resources on the computer and eats up the cpu too.
I also tested this with the linux version of rclone and it also too kept all the ports open and never closing them.

At first, I thought this issue wasn't related to teldrive and look it up to see if this affected only rclone...however when I did, I found nothing related to this error in relation to rclone suggesting this is an error with the teldrive modified rclone only.

Please do look into this, if resolved it'll optimize and improve the speed/resource use of rclone with teldrive!
Thank you.

**Comment by steffen-poulsen** [comment]
+1, seeing this also.

**Comment by vavtnen** [comment]
This also happens when I renamed a lot of files in a short period of time. May be set a shorter time out on rclone side, I dont know if that is even possible

**Comment by divyam234** [comment]
@vavtnen  are  you using teldrive local instance?

**Comment by vavtnen** [comment]
@divyam234 yes. I am using local instance.

**Comment by NiTr0gLiTcH** [comment]
solved in 1.4.8
