### ISSUE TITLE
Getting "panic: JSON decoder out of sync - data changing underfoot?"

### ISSUE THREAD

**Issue by vavtnen** [divyam234/teldrive#249]
Running latest version and getting this error a lot.

panic: JSON decoder out of sync - data changing underfoot?

goroutine 882678 [running]:
encoding/json.(*decodeState).object(0xc011c02990, {0x1aedce0?, 0xc011c02a68?, 0x171bb20?})
        encoding/json/decode.go:677 +0x19b8
encoding/json.(*decodeState).value(0xc011c02990, {0x1aedce0?, 0xc011c02a68?, 0x2?})
        encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).array(0xc011c02990, {0x171bb20?, 0xc00099e6f0?, 0xfdb?})
        encoding/json/decode.go:555 +0x50f
encoding/json.(*decodeState).value(0xc011c02990, {0x171bb20?, 0xc00099e6f0?, 0x9?})
        encoding/json/decode.go:364 +0x74
encoding/json.(*decodeState).object(0xc011c02990, {0x1aea6c0?, 0xc00099e6c8?, 0x199?})
        encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc011c02990, {0x1aea6c0?, 0xc00099e6c8?, 0x6?})
        encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).object(0xc011c02990, {0x1a363e0?, 0xc00099e6c8?, 0x1059?})
        encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc011c02990, {0x1a363e0?, 0xc00099e6c8?, 0x4?})
        encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).object(0xc011c02990, {0x16e28c0?, 0xc00099e6c0?, 0x7fe8749fea88?})
        encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc011c02990, {0x16e28c0?, 0xc00099e6c0?, 0xc022b1c008?})
        encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc011c02990, {0x16e28c0?, 0xc00099e6c0?})
        encoding/json/decode.go:181 +0x11e
encoding/json.Unmarshal({0x7fe87559c069, 0x1064, 0x1064}, {0x16e28c0, 0xc00099e6c0})
        encoding/json/decode.go:108 +0xf9
github.com/gotd/td/session.(*Loader).Load(0x0?, {0x225fbc0?, 0xc0080ab040?})
        github.com/gotd/td@v0.102.0/session/session.go:134 +0x9d
github.com/gotd/td/telegram.(*Client).saveSession(_, {0x8e4c, 0x1, 0x0, 0x1, 0x0, 0x0, 0x666095a6, 0x6660a22c, 0x0, ...}, ...)
        github.com/gotd/td@v0.102.0/telegram/session.go:68 +0x99
github.com/gotd/td/telegram.(*Client).onSession(_, {0x8e4c, 0x1, 0x0, 0x1, 0x0, 0x0, 0x666095a6, 0x6660a22c, 0x0, ...}, ...)
        github.com/gotd/td@v0.102.0/telegram/session.go:120 +0x438
github.com/gotd/td/telegram.clientHandler.OnSession({_}, {0x8e4c, 0x1, 0x0, 0x1, 0x0, 0x0, 0x666095a6, 0x6660a22c, 0x0, ...}, ...)
        github.com/gotd/td@v0.102.0/telegram/conn_builder.go:22 +0x78
github.com/gotd/td/telegram/internal/manager.(*Conn).OnSession(_, {0x80e2e5e181fd84e, {{0x82, 0xc7, 0xa2, 0xe5, 0x99, 0xfa, 0x60, 0x3c, ...}, ...}, ...})
        github.com/gotd/td@v0.102.0/telegram/internal/manager/conn.go:93 +0x1f5
github.com/gotd/td/mtproto.(*Conn).handleSessionCreated(0xc0103d98c8, 0x1b8c6c7?)
        github.com/gotd/td@v0.102.0/mtproto/handle_session_created.go:36 +0x8b5
github.com/gotd/td/mtproto.(*Conn).handleMessage(0xc0103d98c8, 0x666095a6a943d409, 0xc0003976b0)
        github.com/gotd/td@v0.102.0/mtproto/handle_message.go:22 +0x267
github.com/gotd/td/mtproto.(*Conn).processContainerMessage(...)
        github.com/gotd/td@v0.102.0/mtproto/handle_container.go:26
github.com/gotd/td/mtproto.(*Conn).handleContainer(0xc0103d98c8, 0x666095a6a943d409, 0xcb462b75?)
        github.com/gotd/td@v0.102.0/mtproto/handle_container.go:17 +0x132
github.com/gotd/td/mtproto.(*Conn).handleMessage(0xc0103d98c8, 0x666095a6a943d409, 0xc000397680)
        github.com/gotd/td@v0.102.0/mtproto/handle_message.go:28 +0x1d9
github.com/gotd/td/mtproto.(*Conn).consumeMessage(0xc0103d98c8, {0x225fbc0, 0xc01908eb40}, 0xc007509b80?)
        github.com/gotd/td@v0.102.0/mtproto/read.go:83 +0x296
github.com/gotd/td/mtproto.(*Conn).readLoop.func2()
        github.com/gotd/td@v0.102.0/mtproto/read.go:207 +0x8f
created by github.com/gotd/td/mtproto.(*Conn).readLoop in goroutine 882801
        github.com/gotd/td@v0.102.0/mtproto/read.go:198 +0x2c7

**Comment by divyam234** [comment]
@vavtnen  this is not related to teldrive there is undelying bug in gotd which teldrive uses it . For now just disable tg pool or restart teldrive service when program exists.

**Comment by vavtnen** [comment]
How do use disable tg pool? Set --tg-pool-size=0?

Thanks.
