### ISSUE TITLE
[QUESTION]Unable to locate the tables saving file information in postgre database

### ISSUE THREAD

**Issue by AlexEisie** [divyam234/teldrive#251]
Running with docker file and using external postgre:
[db]
data-source = "postgres://postgres:<password>@127.0.0.1/teldrive"

Uploaded a few files and try to locate the database which teldrive specific files in telegram channel according to.
sudo -u postgres psql -d teldrive
\dt
              List of relations
 Schema |       Name       | Type  |  Owner   
--------+------------------+-------+----------
 public | goose_db_version | table | postgres
(1 row)

so where is the file storage table?

**Comment by azeyrx** [comment]
files table stores the information; 
uploads table the parts of the files;
