### ISSUE TITLE
Errors:  ignored key without a value & failed to delete messages 

### ISSUE THREAD

**Issue by Xabiman** [divyam234/teldrive#252]
Hello.

When I launch Teldrive I'm getting there two errors:
ERROR: ignored key without a value
ERROR: failed to delete messages 
Do you know why I'm getting this and how to solve it?
Thanks in advance.

**Comment by NiTr0gLiTcH** [comment]
same, happens on start up

```
INFO  Started server http://localhost:8032
DEBUG  User Session  {"id": **, "username": "**"}
ERROR  Ignored key without a value.  {"ignored": null}
ERROR  failed to delete messages
```

it's a minor issue tho, popped up first after the `uploads_pkey` migration.
i manually changed the primary key at the time and didn't update when there was the typo.

**Comment by Xabiman** [comment]
> same, happens on start up
> 
> ```
> INFO  Started server http://localhost:8032
> DEBUG  User Session  {"id": **, "username": "**"}
> ERROR  Ignored key without a value.  {"ignored": null}
> ERROR  failed to delete messages
> ```
> 
> it's a minor issue tho, popped up first after the `uploads_pkey` migration. i manually changed the primary key at the time and didn't update when there was the typo.

I understand. Thank you for your reply. And do you know how to solve it? Is there something to do?

**Comment by NiTr0gLiTcH** [comment]
no, i didn't look into it that much.

i was just adding up some information to your issue.

**Comment by xd003** [comment]
Just for info, got this on v1.3.4 as well
