### ISSUE TITLE
[Guide] need a proper guide 

### ISSUE THREAD

**Issue by namanbansal02** [divyam234/teldrive#253]
I had already setup the app through docker.. need some proper guide on setting up with rclone help would be really appreciated

**Comment by iwconfig** [comment]
What do you want to know? i don't think there is a ready made docker version of divyam234's rclone fork if that's what you're looking for.

I suggest you install the rclone fork on your host machine, from where you want to access your teldrive.

https://github.com/divyam234/rclone/releases/tag/v1.66.3

If you're installing from zip file:

- unzip the file
- cd into the unzipped folder 
- `sudo mv -v rclone /usr/local/bin`

Put this in your rclone config file, and change `api_host` and `access_token`:

```ini
[teldrive]
type = teldrive
api_host = http://localhost:8080 # default host
access_token = #session token obtained from cookies
chunk_size = 500M
upload_concurrency = 4
encrypt_files = false # Enable this to encrypt files make sure ENCRYPTION_KEY env variable is not empty in teldrive instance.
random_chunk_name= true # Use random chunk names when uploading files to channel instead of original filename.
```

if you need further help with configuring rclone, [read the rclone documentation here](https://rclone.org/commands/rclone_config/). To quickly find out where to put the config file, run `rclone config file`.

If you're using ~Linux~*nix just run

```bash
nano "$(rclone config file | tail -1)"
```

and copy/paste the above (with your api host and access token ofc).

Access token is the value of `user-session` in the cookies for the web UI of teldrive, starting with "ey"

![image](https://github.com/divyam234/teldrive/assets/10843441/d626d5ba-fa0b-44ad-be82-dfe897afc3e9)


Now you access your teldrive via rclone like this, for example:

```sh-session
$ rclone lsf teldrive:
my-pr0n-collection/
memes/
diary.txt
```

or 

```sh-session
$ rclone tree teldrive:
/
├── my-pr0n-collection
│   ├── [REDACTED]
├── memes
│   ├── kitty.jpg
├── diary.txt
```

or

```sh-session
$ rclone mount teldrive:/my-pr0n-collection/[REDACTED]/[REDACTED]/[VERY_REDACTED] --vfs-cache-mode full --cache-dir $HOME/pr0nnn --allow-other --daemon
ls ~/pr0nnn
[OMFG]
```

`teldrive:` is the name of your rclone remote, which you've defined in your config file with `[teldrive]`. You can change it to whatever you want.

---

if you want to use a docker version of divyam234's rclone fork, download the source code and build the Dockerfile yourself.

https://github.com/divyam234/rclone/archive/refs/heads/main.zip

I won't help you with that tough.

## And last but not least: [RTFM](https://rclone.org/docs/)

**Comment by pinguim16** [comment]
@iwconfig i can run windows? (sorry for my question)

**Comment by iwconfig** [comment]
> @iwconfig i can run windows? (sorry for my question) If so, could you tell me what you would call the tel drive with it in Windows?

not sure what you mean. You want to know how to install `rclone` in windows? Well, read the documentation, then follow what i wrote to OP. Begin here: https://rclone.org/install/#windows but download divyam234's fork of `rclone` instead of the upstream official one.

**Comment by the4anoni** [comment]
> ```ini
> random_chunk_name= true
> ```

Hi
I tried using config from `rclone config` and template provided by you, both don't work, I am getting following error:

```bash
rclone lsf teldrive:
2024/10/25 14:28:47 CRITICAL: Failed to create file system for "teldrive:": Get "http://localhost:8080/api/auth/session": dial tcp [::1]:8080: connect: connection refused
```

Do you have any idea what I could do wrong? Here is my config:

```
[teldrive]
type = teldrive
access_token = [redacted, value from user-session cookie]
api_host = http://localhost:8080
channel_id = [redacted], using ID format without "-"
encrypt_files = true
```
