### ISSUE TITLE
Deleting files & database size 

### ISSUE THREAD

**Issue by Xabiman** [divyam234/teldrive#254]
If I delete a Teldrive folder with a lot of files inside, will my Neon database size decrease?
I've some folders with video files that seems to be corrupted, those videos get error when trying to play (all videos of the same folders). I'm going to delete those folders and re-upload them again, but I'm not sure what will happen with my Neon database size...

**Comment by steffen-poulsen** [comment]
Yes, the neon database size will decrease automatically as the number of rows in the files table decreases. There is no need to run an "optimize" pgsql command or similar.

I hit an [undocumented 1.000.000 file limit for Telegram channels ](https://github.com/divyam234/teldrive/issues/242) recently, making some files and folders disappear for me also.

If you happen to have hit the same limit, uploading these videos again will unfortunately make some other files disappear.

Just a heads up :-)

**Comment by Xabiman** [comment]
Thanks @steffen-poulsen for your help. Unfortunatelly my database size doesn't decxrease deleting files (I have lots of dupplicate files for my mistake), I have deleted them but the database size does't decrease. Do you knw how to solve this with no risk?

**Comment by steffen-poulsen** [comment]
> Do you knw how to solve this with no risk?

[Xabiman](https://github.com/Xabiman): The only thing I can think of, would be some kind of retention going on?

You can learn about WAL-records and retention here: https://neon.tech/docs/introduction/usage-metrics
