### ISSUE TITLE
Unable to rename / delete folders on latest version.

### ISSUE THREAD

**Issue by vavtnen** [divyam234/teldrive#257]
teldrive and rclone are lastest version.

11/06/2024 09:37 AM     INFO             {"status": 200, "method": "POST", "path": "/api/files/delete", "query": "", "ip": "::1", "user-agent": "rclone/v1.66.3", "latency": 0.172498278, "time": "2024-06-11T09:37:06Z"}
11/06/2024 09:40 AM     INFO             {"status": 200, "method": "GET", "path": "/api/files", "query": "nextPageToken=&op=list&path=%2F&perPage=500&sort=id", "ip": "::1", "user-agent": "rclone/v1.66.3", "latency": 0.496674591, "time": "2024-06-11T09:40:34Z"}

**Comment by azeyrx** [comment]
Try using new rclone/v1.66.4 & teldrive/v1.3.6

**Comment by vavtnen** [comment]
It works. Thanks
