### ISSUE TITLE
Question: Is it possible to add more than 50 bots per channel?

### ISSUE THREAD

**Issue by vavtnen** [divyam234/teldrive#258]
I am getting TOO_MANY_ADMIN error. Wouldn't it be possible to add more bots as none admin just for downloading/uploading purposes?

**Comment by azeyrx** [comment]
50 should easily be enough, note the README... you should use the storage space responsibly.

**Comment by Imaje3d** [comment]
no

**Comment by vavtnen** [comment]
Notice. Thanks
