### ISSUE TITLE
Option to deploy to Heroku

### ISSUE THREAD

**Issue by pr0b35** [divyam234/teldrive#269]
Maybe you could add a feature that allows deploying this app to Heroku? So it can be accessed everywhere, similar to what's described in https://github.com/mgilangjanuar/teledrive

**Comment by pr0b35** [comment]
Thanks for the response!!

Is there an instruction or documentation available for deploying this app on a VPS?

**Comment by xd003** [comment]
> Thanks for the response!!
> 
> Is there an instruction or documentation available for deploying this app on a VPS?

yes, the readme has everything you would need, i would just recommended using the docker compose to deploy it through docker

**Comment by pr0b35** [comment]
> > Thanks for the response!!
> 
> > 
> 
> > Is there an instruction or documentation available for deploying this app on a VPS?
> 
> 
> 
> yes, the readme has everything you would need, i would just recommended using the docker compose to deploy it through docker

Okay thanks for the recs, will try it
