### ISSUE TITLE
Video playback incorrect aspect ratio

### ISSUE THREAD

**Issue by musahi0128** [divyam234/teldrive#27]
Hi, I've got some video files with different aspect ratio, but seems like the player force them the play on exactly 1280x720px. It would be great if the player can show the video in its correct aspect ratio. Scale down to fit 1280px width will also be cool. And if the player can support subtitles/captions that will be also superb. Thanks!

**Comment by divyam234** [comment]
@musahi0128 that one is fixed migrated to new player library where you can dynamically change aspect ratio and pdf viewer is also fixed

**Comment by musahi0128** [comment]
Whoa it's beautiful, gonna check out the pdf too. Thanks!
