### ISSUE TITLE
Version 1.4.0 / 1.4.1 / 1.4.2 no Access from RClone

### ISSUE THREAD

**Issue by Crypt0x69** [divyam234/teldrive#274]
Since Version 1.4.0 its not possible anymore to Access Files via RClone.

Enc on RClone / TelDrive is enabled.

tg.stream on/off makes no difference.

Logs:

Teldrive:

4/06/2024 12:53 PM	ERROR	file streamfile is too short to be encrypted
24/06/2024 12:53 PM	INFO		{"status": 500, "method": "GET", "path": "/api/files/veRZXSpakflucyQL/stream/VA+-+It's+Coffee+Time!+-+Vol.+1+(Mixed+by+DJ+Kosta).mp3", "query": "hash=83fe09175fce6c9ac2dae7b4c9ae071b", "ip": "::1", "user-agent": "rclone/", "latency": 0.039643807, "time": "2024-06-24T10:53:53Z"}

Rclone:

2024/06/24 12:53:59 DEBUG : pacer: low level retry 1/10 (error error reading error out of body: unexpected EOF)

**Comment by divyam234** [comment]
repull new image should be working now
