### ISSUE TITLE
Version 1.4.3 = Segfault on AMD64

### ISSUE THREAD

**Issue by Crypt0x69** [divyam234/teldrive#279]
``anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x16834e7]

goroutine 1 [running]:
github.com/divyam234/teldrive/cmd.bindFlags(0xc000024000, {0xc000234706, 0x7}, {0x19c3380?, 0xc0000c7a40?, 0x19c3380?})
	github.com/divyam234/teldrive/cmd/run.go:187 +0x387
github.com/divyam234/teldrive/cmd.bindFlags(0xc000024000, {0x0, 0x0}, {0x1a62740?, 0xc0000c7a40?, 0xc0000c7a50?})
	github.com/divyam234/teldrive/cmd/run.go:181 +0x5c5
github.com/divyam234/teldrive/cmd.initViperConfig(0xc000000308)
	github.com/divyam234/teldrive/cmd/run.go:168 +0x3b1
github.com/divyam234/teldrive/cmd.NewRun.func2(0xc000024000?, {0x1bdc764?, 0x4?, 0x1bdc768?})
	github.com/divyam234/teldrive/cmd/run.go:48 +0x13
github.com/spf13/cobra.(*Command).execute(0xc000000308, {0x32504e0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.1/command.go:956 +0x951
github.com/spf13/cobra.(*Command).ExecuteC(0xc000000008)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(0x22d2f90?, {0x22d3150?, 0xc000531580?})
	github.com/spf13/cobra@v1.8.1/command.go:1034 +0x47
main.main()
	./main.go:15 +0x96

**Comment by divyam234** [comment]
repull image should be working now
