### ISSUE TITLE
Use different address and port

### ISSUE THREAD

**Issue by musahi0128** [divyam234/teldrive#28]
Hi, I was using the compiled version of the apps.
I run it on my Windows PC, and it works flawlessly. I can access it on `http://localhost:8080`.
But when I run it on my Linux server and seems like my 8080 port is already used, the apps are not able to run.
Is there any way to set the address and port where the service will listen to?
If that was not a feature currently available, would you please add it so we can change the address and port from the .env file?
Thanks!

**Comment by divyam234** [comment]
@musahi0128  it's supported use env variable read readme

**Comment by musahi0128** [comment]
Hi, I'm sorry if it was addressed already but I can't seem to find where it is mentioned.
Also, would you please let me know the Discord links? thanks!

**Comment by xd003** [comment]
Hello @divyam234 
Can i too have the discord link please, i can't find it anywhere

**Comment by xd003** [comment]
> Hi, I'm sorry if it was addressed already but I can't seem to find where it is mentioned

Take a look at Optional Vars - ```PORT```

**Comment by musahi0128** [comment]
> Hello @divyam234 Can i too have the discord link please, i can't find it anywhere

https://discord.gg/J2gVAZnHfP
It was on the main page look tiny with status of how many online people, no idea that was the button lol.

**Comment by musahi0128** [comment]
> > Hi, I'm sorry if it was addressed already but I can't seem to find where it is mentioned
> 
> Take a look at Optional Vars - `PORT`

You can also use `HOST` to change which ip address you want the server to listen to
