### ISSUE TITLE
Broken right click/context menu on Firefox

### ISSUE THREAD

**Issue by X41** [divyam234/teldrive#29]
Hi
I just realised that it is not possible to right click on uploaded files in Firefox. Instead i get a JS error in the console. Verified it's not an issue on my end by installing a fresh copy on a VM and trying it again there

![bruh](https://github.com/divyam234/teldrive/assets/2126863/4086d385-0248-4080-acc4-e182e5324e4e)

**Comment by divyam234** [comment]
Its working fine on my firefox try to disable harware acceleration its a known bug in firefox otherwise try diff browsers

**Comment by X41** [comment]
Could it be that you've got a device with a Touch input? i tried disabling hardware acceleration and dug a little deeper into why `Touch` would not exist within firefox and found this

![bruh](https://github.com/divyam234/teldrive/assets/2126863/bfc86e68-e5ff-4678-b92e-003f5db32a01)

then i tested it with simulated touch inputs and it started working on Firefox. looks like chrome is always okay with it, but Firefox just does not know about the `Touch` interface unless a supported device has been connected apparently. Is there a way to check for it? maybe prepending that to the if statement in the event handler should take care of this issue

**Comment by divyam234** [comment]
@X41 what is the out of window.TouchEvent  in you firefox console

**Comment by X41** [comment]
` window.TouchEvent` is `Undefined` if not in touch simulated mode. I've joined the discord server there, feel free to message me i'll try to get back to you asap 👍

**Comment by divyam234** [comment]
fixed in latest build
