### ISSUE TITLE
Upload folder directly

### ISSUE THREAD

**Issue by akang943578** [divyam234/teldrive#290]
Currently we can only upload files and create folder. Can we add the function of upload folder directly?

![image](https://github.com/divyam234/teldrive/assets/17521632/76f2de76-776a-4351-9900-32ea3c4f9b69)

**Comment by xd003** [comment]
you can use cli to upload folder

**Comment by Pe0xonN** [comment]
> you can use cli to upload folder

cli is rclone?

**Comment by xd003** [comment]
> cli is rclone?

yes

**Comment by Cohinem** [comment]
He did say he would add folder upload + drag and drop... but that was like 4 months ago, [here](https://github.com/divyam234/teldrive/discussions/121#discussioncomment-8424217). 

I also think these are important quality of life features. And I'm pretty sure I've seen them being suggested before. either here or on discord.

**Comment by KiraSokolov** [comment]
drag and drop must have 10/10
