### ISSUE TITLE
Problem uploading files and question

### ISSUE THREAD

**Issue by dceldran** [divyam234/teldrive#3]
Hi, after i do login into web interface i can create new folders but i can't upload any file, i receive this API error:

```
2023/08/17 17:29:12 [Recovery] 2023/08/17 - 17:29:12 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x44f7b7)
/usr/local/go/src/runtime/signal_unix.go:861 (0x44f785)
/app/utils/tgclient.go:175 (0x135d120)
/app/services/upload.service.go:70 (0x135c571)
/app/routes/upload.go:34 (0x135f985)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x135f4db)
/app/routes/middleware.go:40 (0x135f413)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x130704a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:172 (0x1370084)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1313f59)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x1313f47)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x13130fd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x13130cc)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x13121ba)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x1311e4d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x131197c)
/usr/local/go/src/net/http/server.go:2938 (0x770a6d)
/usr/local/go/src/net/http/server.go:2009 (0x76c953)
/usr/local/go/src/runtime/asm_amd64.s:1650 (0x46b5e0)
```

And one question i have, when i can upload, download and delete files, how can i use this middleware with rclone?

thanks!!

**Comment by divyam234** [comment]
@dceldran  Are you using MULTI_CLIENT=true  if you then  you have to provide  bot tokens otherwise keep it false. Rclone will work but first I want to make this api stable  mainly  fix major bugs if users are facing during onboarding.

**Comment by dceldran** [comment]
@divyam234 thanks for the answer. I have MULTI_CLIENT=true but i have 5 bots added to a group with admin permissions and i put the 5 bot tokens into .env file.

```
MULTI_CLIENT=true
MULTI_TOKEN1=xxxx
MULTI_TOKEN2=xxxx
MULTI_TOKEN3=xxxx
MULTI_TOKEN4=xxxx
MULTI_TOKEN5=xxxx
```

I also tried to put MULTI_CLIENT=false with the same result

My CHANNEL_ID is a negative number, i also tried to put it in positive or in negative and same result.

thanks!

**Comment by dceldran** [comment]
Okey i can fix some issues.

The first problem i have is profile photo, if you don't have any profile photo in telegram, just didn't work.

When i put my photo in telegram, and i put MULTI_CLIENT=false, i can upload files. Now the problem is i can't upload files with MULTI_CLIENT=true but i add the bots to the channel with admin permissions and i put the .env file like i post in my last message.

Now the error i'm receiving is:

```
2023/08/18 08:44:09 [Recovery] 2023/08/18 - 08:44:09 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:261 (0x44f7b7)
/usr/local/go/src/runtime/signal_unix.go:861 (0x44f785)
[GIN] 2023/08/18 - 08:44:09 | 500 |   43.601513ms |     192.168.0.1 | POST     "/api/uploads/e961b70d354f783ecf5d4f270d22f29dd5bb42a4?fileName=log.txt&partNo=1&totalparts=1"
/app/services/upload.service.go:71 (0x135d12b)
/app/routes/upload.go:34 (0x135f985)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x135f4db)
/app/routes/middleware.go:40 (0x135f413)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x130704a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:172 (0x1370084)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1313f59)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x1313f47)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x13130fd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x13130cc)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x13121ba)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x1311e4d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x131197c)
/usr/local/go/src/net/http/server.go:2938 (0x770a6d)
/usr/local/go/src/net/http/server.go:2009 (0x76c953)
/usr/local/go/src/runtime/asm_amd64.s:1650 (0x46b5e0)
```

thanks!

**Comment by dceldran** [comment]
@divyam234 I was doing some research about the MULTI_CLIENT=true and you have right, the clients don't start. 

I'm doing my tests in my local machine and i can solve this issue if i modify docker-compose.yml and stop using your server image and start building the image locally with the Dockerfile you've provided. When i do in that way i can see all the "started Client" messages, one per bot.

Another tries i'm doing is in another server, is a low spec old server and i already tried your docker image and building a locally image and it still don't works, i don't see the messages "started Client".

I also tried to do test in another server but is arm and the server and the client containers are not working in the arm platform.

Thanks for all your job, really this project is awesome

**Comment by divyam234** [comment]
@dceldran I haven't published  it for arm yet as very few people uses it.But I will release binaries of app for all platforms which will mitigate the use of docker at all . Once app become stable enough.
