### ISSUE TITLE
DB Migration issues: Invalid path error on certain directories & my-drive homepage wouldn't load

### ISSUE THREAD

**Issue by xd003** [divyam234/teldrive#304]
Ever since migrating to the PGroonga database along with all its recent changes, i have noticed that atleast 10% of my directories display this error when trying to open them. The size column displays 0B for such directories. All of the other files and directories show up totally fine. Its happening only in certain directories/paths

![image](https://github.com/user-attachments/assets/bdd0299b-cca8-4c5d-9977-b2aee65e20a9)

db: `groonga/pgroonga:latest-debian-16` (previously on postgres 16 latest image which uses debain by default)
teldrive: `v1.4.11`

**Comment by divyam234** [comment]
Path will invalid only if its not present.``select * from teldrive.get_file_from_path('/test', tguserid)`` you can eun this to see  if path is valid  relplace tguserid with telegram user id.

**Comment by divyam234** [comment]
This is fine you  have missing folders in databse in database for  this path ``/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]`` try to check for every folder separetely

**Comment by DevRush94** [comment]
> > select * from teldrive.get_file_from_path('/test', tguserid)
> 
> Getting this response from SQL - `SQL Error [P0001]: ERROR: file not found for path: /Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755] Where: PL/pgSQL function teldrive.get_file_from_path(text,bigint) line 43 at RAISE`
> 
> Here's the whole log from teldrive when opening that directory if it helps
> 
> ```
> 2024/07/15 13:30:48 goose: no migrations to run. current version: 20240715001936
> 15/07/2024 01:30 PM  INFO  Started server http://localhost:8080
> 15/07/2024 01:32 PM  INFO    {"status": 200, "method": "GET", "path": "/api/files", "query": "page=1&limit=500&order=asc&sort=name&path=%2FMedia%2FAnimated+Movies", "ip": "103.44.106.30", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0", "latency": 0.110719102, "time": "2024-07-15T13:32:59Z"}
> 15/07/2024 01:33 PM  ERROR  [DB] github.com/divyam234/teldrive/pkg/services/file.go:329 ERROR: file not found for path: /Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755] (SQLSTATE P0001)
> [38.313ms] [rows:-] WITH "ranked_scores" AS (SELECT "name",count(*) OVER () as total,ROW_NUMBER() OVER (ORDER BY name ASC) AS rank FROM "teldrive"."files" WHERE user_id = 6362481266 AND status = 'active' AND parent_id in (SELECT id FROM teldrive.get_file_from_path('/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]', 6362481266))) SELECT *,(select total from ranked_scores limit 1) as total FROM "teldrive"."files" WHERE name >= (SELECT name FROM ranked_scores WHERE rank = 1) AND (user_id = 6362481266 AND status = 'active' AND parent_id in (SELECT id FROM teldrive.get_file_from_path('/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]', 6362481266))) ORDER BY "name" LIMIT 500
> 15/07/2024 01:33 PM  ERROR  record not found
> 15/07/2024 01:33 PM  INFO    {"status": 404, "method": "GET", "path": "/api/files", "query": "page=1&limit=500&order=asc&sort=name&path=%2FMedia%2FAnimated+Movies%2FMortal+Kombat+Legends+Battle+of+the+Realms+%282021%29+%5Btmdbid-841755%5D", "ip": "103.44.106.30", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0", "latency": 0.03868104, "time": "2024-07-15T13:33:05Z"}
> 15/07/2024 01:33 PM  ERROR  [DB] github.com/divyam234/teldrive/pkg/services/file.go:329 ERROR: file not found for path: /Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755] (SQLSTATE P0001)
> [39.331ms] [rows:-] WITH "ranked_scores" AS (SELECT "name",count(*) OVER () as total,ROW_NUMBER() OVER (ORDER BY name ASC) AS rank FROM "teldrive"."files" WHERE user_id = 6362481266 AND status = 'active' AND parent_id in (SELECT id FROM teldrive.get_file_from_path('/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]', 6362481266))) SELECT *,(select total from ranked_scores limit 1) as total FROM "teldrive"."files" WHERE name >= (SELECT name FROM ranked_scores WHERE rank = 1) AND (user_id = 6362481266 AND status = 'active' AND parent_id in (SELECT id FROM teldrive.get_file_from_path('/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]', 6362481266))) ORDER BY "name" LIMIT 500
> 15/07/2024 01:33 PM  ERROR  record not found
> ```
> 
> These are not new files/directories but pretty old and their files are still present on the telegram channel, only started happening after the recent update

+1

**Comment by xd003** [comment]
> This is fine you have missing folders in database for this path `/Media/Animated Movies/Mortal Kombat Legends Battle of the Realms (2021) [tmdbid-841755]` try to check for every folder separetely for same userid.

Just checked many of them, not all folders with 0B size has this issue. Half of them contain files inside them, its just not updated in the outer folder for some reason. For the other half folders, i can reproduce this issue with each of them ( maybe like 5% can say). What do i do now then ? Delete all these folders from the web and reupload ?

**Comment by divyam234** [comment]
Are you able to list files by parentId of the folder?

**Comment by xd003** [comment]
> Are you able to list files by parentId of the folder?

i definitely can list files by parentId, zero no issues with that

**Comment by divyam234** [comment]
> > Are you able to list files by parentId of the folder?
> 
> i definitely can list files by parentId, zero no issues with that. This is very same file/directory from above error
> 
> ![image](https://private-user-images.githubusercontent.com/26503185/348734985-ef0616c9-3f19-497b-a50e-ebe40159679a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTI4MTMsIm5iZiI6MTcyMTA1MjUxMywicGF0aCI6Ii8yNjUwMzE4NS8zNDg3MzQ5ODUtZWYwNjE2YzktM2YxOS00OTdiLWE1MGUtZWJlNDAxNTk2NzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODIyZTc1MDFiNjcyNGViODVmYjZjMmZlOWVlZDAwMTE5YmQ3MDZkZWMxMjlmYmE3MDY5MWVjZjM4NWI0MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WDSuCYfjIKT2a1yv5nE8enBEu0K7VbEzOHIuXsrQnzU)

Are you able to enter inside first folder?

**Comment by divyam234** [comment]
```sql
WITH RECURSIVE dir_hierarchy AS (
        SELECT
            root.id,
            root.name,
            root.parent_id,
            0 AS depth,
            '' as path
        FROM
            teldrive.files as root
        WHERE
            root.parent_id = 'root' AND root.user_id = uid
        
        UNION ALL
        
        SELECT
            f.id,
            f.name,
            f.parent_id,
            dh.depth + 1 AS depth,
            dh.path || '/' || f.name
        FROM
            teldrive.files f
        JOIN
            dir_hierarchy dh ON dh.id = f.parent_id
        WHERE f.type = 'folder' AND f.user_id = uid
    )
select * from dir_hierarchy;
```
Can you run this query ans see whether path is listed or not .

**Comment by xd003** [comment]
> Can you run this query ans see whether path is listed or not at `3 ` depth .try for all possible user id if yo have multiple accounts

The problematic paths causing error are not listed with this script. i have always had single user in `jwt -> allowed-users`

**Comment by xd003** [comment]
@divyam234 
I would like to point a slight difference i noticed. If i roll back to the previous version 1.4.10, i no longer see these problematic directories in the web normally. Only way i can find them if from a search browsing by parentID. In the current version, they are visible on the web but i can't open them as mentioned in this thread

**Comment by xd003** [comment]
> @xd003 can browse the folder in rclone

 i can view that folder with `rclone lsd` in its parent folder
 With `rclone ls` on directly on that folder, it returns - 
 ```
 ERROR : : error listing: directory not found
 Failed to ls with 2 errors: last error was: directory not found
 ```
 In rclone mount, it appears as a empty folder

**Comment by xd003** [comment]
@divyam234 i thought i would just delete one of these problematic drectories and reupload them to see if it gets fixed.
But that folder is not getting deleted at all, deleted it from the normal web listing and also after searching for it explicitly and deleting its folder but it just doesn't get deleted, the files are still in telegram channel and so is that empty directory in the web

**Comment by xd003** [comment]
![image](https://github.com/user-attachments/assets/d55ace63-08b1-4331-9f7f-3d71ba823e51)

Don't know what's really going on here, randomly nothing would show up on the `/my-drive` homepage. `/recent` and `/storage` show up totally fine, 

Teldrive docker doesn't report any error. I had taken a database backup before migrating to pgroonga + teldrive update. Will roll back both the db and teldrive version to older one for now

**Comment by SingingDalong** [comment]
In my case, the problem occurred when I used the 127.0.0.1 address. I changed the URL address to localhost and the problem was solved.

**Comment by xd003** [comment]
> In my case, the problem occurred when I used the 127.0.0.1 address. I changed the URL address to localhost and the problem was solved.

Good for you, i am running this on a remote server so not sure what would fix it. Uploading still seems to work fine when this happens

**Comment by kreuber** [comment]
I'm also generally hit by this. When switching to PGroonga I receive this on the main page /my-drive
![Screenshot 2024-07-18 at 11 03 36](https://github.com/user-attachments/assets/8c0e65c1-7cb5-4a71-aac8-4a26f559bfc0)

In the Postgres Log it looks like this:
```
2024-07-18 09:04:07.262 UTC [769] ERROR:  file not found for path:
2024-07-18 09:04:07.262 UTC [769] CONTEXT:  PL/pgSQL function get_file_from_path(text,bigint) line 43 at RAISE
2024-07-18 09:04:07.262 UTC [769] STATEMENT:  select * from teldrive.get_file_from_path($1, $2)
```

And the Teldrive log has:
```
18/07/2024 09:04 AM	ERROR	[DB] github.com/divyam234/teldrive/pkg/services/file.go:326 ERROR: file not found for path:  (SQLSTATE P0001)
[53.231ms] [rows:-] select * from teldrive.get_file_from_path('/', xxxxx)
18/07/2024 09:04 AM	ERROR	ERROR: file not found for path:  (SQLSTATE P0001)
```

I also tested the DB with TD 1.4.9, 1.4.10 and 1.4.11 so it seems to be DB related? When switching back to 1.4.9 and Bitnami PG Docker it's fine.

**Comment by kreuber** [comment]
1.4.12:
![Screenshot 2024-07-18 at 14 26 37](https://github.com/user-attachments/assets/df340ef4-d097-4e39-825b-88f9e5492b73)

**Comment by xd003** [comment]
> 1.4.12: ![Screenshot 2024-07-18 at 14 26 37](https://private-user-images.githubusercontent.com/86347852/349953358-df340ef4-d097-4e39-825b-88f9e5492b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDgwOTYsIm5iZiI6MTcyMTMwNzc5NiwicGF0aCI6Ii84NjM0Nzg1Mi8zNDk5NTMzNTgtZGYzNDBlZjQtZDA5Ny00ZTM5LTgyNWItODhmOWU1NDkyYjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MGZkNmEyZDJlZmMzNjgwMzE0ZTBkODYxOGM1ODA3ZDY5NTE4YTU2YWE4OGJhODQ4MWVmNjM5NThlYTI5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOigRRpjMMvStEfXOb7FPld8aC9FcrxGPBnTmZXPOBk)

can confirm, i am also facing the same issue even on 1.4.12

**Comment by xd003** [comment]
@divyam234 Apart from the above error that /my-drive would just up empty, i can confirm that the original issue ie. certain directories show up with invalid path is still present for me on latest v1.4.12

**Comment by divyam234** [comment]
@xd003  I can't reproduce it  I  needed  dump of folders entries to see where the problem lies

**Comment by xd003** [comment]
> @xd003 I can't reproduce it I need dump of folders entries to see where the problem lies.You can dump json or csv of only folders from dbeaver.

I am attaching the dump of folders along with this post. i would also like to mention the `/my-drive` issue atleast seems random, it shows up at times on its own for sometime. At the time of exporting this dump, `/my-drive` was loading fine for me
[folders_dump.json](https://github.com/user-attachments/files/16302684/folders_dump.json)

**Comment by divyam234** [comment]
I can list all directories from your data no errors also the  problematic folders

**Comment by divyam234** [comment]
You might have messed up data restore process.Do one thing rerun the migrations on new db and restore only data not schema when using pg_restore.

**Comment by xd003** [comment]
> You might have messed up data restore process.Do one thing rerun the migrations on new db and restore only data not schema when using pg_restore.

Just to confirm, did we had to do `pg_restore` on newly  created pgroonga db ?
I did take a backup with pg backup but didn't used pg restore, just changed the docker image in compose and recreated the container.

**Comment by divyam234** [comment]
No its not needed but not sure why its not working for you.

**Comment by xd003** [comment]
> No its not needed but not sure why its not working for you.

I see, i will try restore process as you told and see how it goes ?
I am assuming the random `my-drive` showing empty is also part of this db migration issue ?

**Comment by xd003** [comment]
i can confirm that all of the aforemention issues are related to database migration, still unsure what caused it in first place but my old postgres backup with v1.4.9 is working perfectly fine

Will update thread as i have more inputs/findings

**Comment by xd003** [comment]
After resotoring my backup from postgres, i just changed the docker image to pgroonga and rebuilt the container. I started teldrive only after this and the migrations ran well and it seems to be fine now, not facing those issues atm. Not sure what caused it in first place earlier but closing it for now

**Comment by phanirithvij** [comment]
Make sure you back up your database first!!

This worked for me for v1.4.13 (updated from 1.4.9 likely, I don't know)

After the update, I noticed a new `root` entry in the files table. I dropped the one where size was NULL (there were two root rows, and the other one had a valid size). Then, I ran `REINDEX DATABASE teldrive;` and everything worked fine.

Be careful which `root` row you drop!

**Comment by aniel300** [comment]
@phanirithvij how and where do i run REINDEX DATABASE teldrive;

**Comment by phanirithvij** [comment]
Might be outdated since the db I see has different id format (uuid). But no harm in re-indexing if you don't remove anything so up to you.

I personally used beekeeper-studio and connected to the postgres db localhost:5432 with teldrive user, password provided in the docker compose file, POSTGRES_PASSWORD=***, and teldrive db.

Alternatively you can use `docker exec -t teldrive_db psql -U teldrive` and do it there but for some reason it didn't work for me.

**Comment by phanirithvij** [comment]
email me at `madlad at duck dot com`, let's discuss there.
