### ISSUE TITLE
add back support for neon db

### ISSUE THREAD

**Issue by D0nnieD4rk0** [divyam234/teldrive#312]
i dont need any extra multilingual search features and i dont know how to migrate to whatever other new db is recomended. or at least provide instructions on how one would migrate. neon should still be supported imo

thanks

**Comment by iwconfig** [comment]
I think it will be better for you and everyone else in the long run to go with something other than Neon db.

Although much of this should work for local postgresql instance as well, if you choose Supabase, here's how I did it:

1. Migrate the database from neon to supa by following these instructions: https://supabase.com/docs/guides/resources/migrating-to-supabase/postgres?queryGroups=migrate-method&migrate-method=cli#migrate-the-database

2. Disable pre-compiled SQL statements and database pooling. Here's how that is defined in a `.toml` config file:

    ```toml
    [db]
    data-source = "postgresql://..."
    prepare-stmt = false
    # etc...
    
    [db.pool]
    enable = false
    # etc...
    ```

3. That's it. Restart your teldrive instance pointing to the new postgesql address.

On my host i had a problem with a too old installed version of `pg_dump`, so i launched a bind-mounted docker container of the latest alpine image, installed `postgresql-client` and went on from there. If you for some reason can't use docker or don't know how, maybe migrating using [the provided Colab notebook will work better for you.](https://supabase.com/docs/guides/resources/migrating-to-supabase/postgres?queryGroups=migrate-method&migrate-method=colab#migrate-the-database)

And if you choose to run it locally (or self-host on a VPS): I'm not entirely sure, but i don't think `db.prepare-stmt=false` and `db.pool.enable=false` are necessary when running a local `pgroonga` instance.

---

### Bonus:

- [Here's a nifty github workflow](https://supabase.com/docs/guides/cli/github-action/backups#periodic-backups-workflow) for automatically backing up your Supabase db to a **(PRIVATE!)** github repository. Super easy!

**Comment by D0nnieD4rk0** [comment]
@iwconfig thanks man, that did the trick
