### ISSUE TITLE
Version 1.4.12 not starting (SQL Problem)

### ISSUE THREAD

**Issue by Crypt0x69** [divyam234/teldrive#316]
I'am using Neon DB.

``/teldrive run
panic: failed run migrate: ERROR 20240711163538_search.sql: failed to run SQL migration: failed to execute SQL query "CREATE EXTENSION IF NOT EXISTS pgroonga;\nDROP INDEX IF EXISTS teldrive.name_search_idx;\nDROP FUNCTION IF EXISTS  teldrive.get_tsquery;\nDROP FUNCTION IF EXISTS teldrive.get_tsvector;\nCREATE INDEX name_search_idx ON teldrive.files USING pgroonga (REGEXP_REPLACE(name, '[.,-_]', ' ', 'g')) WITH (tokenizer = 'TokenNgram');": ERROR: extension "pgroonga" is not available (SQLSTATE 0A000)

goroutine 1 [running]:
github.com/divyam234/teldrive/internal/database.NewDatabase(0xc0004a2000)
	github.com/divyam234/teldrive/internal/database/database.go:63 +0x4cb
reflect.Value.call({0x181ff20?, 0x20cf350?, 0x7f6412f5df38?}, {0x1bc7258, 0x4}, {0xc000010498, 0x1, 0x7f6412f4da48?})
	reflect/value.go:596 +0xca6
reflect.Value.Call({0x181ff20?, 0x20cf350?, 0x411f85?}, {0xc000010498?, 0x1972f00?, 0xc0004ed501?})
	reflect/value.go:380 +0xb9
go.uber.org/dig.defaultInvoker({0x181ff20?, 0x20cf350?, 0xc000060db0?}, {0xc000010498?, 0x1?, 0x22de3f0?})
	go.uber.org/dig@v1.17.1/container.go:238 +0x25
go.uber.org/dig.(*constructorNode).Call(0xc0005b8600, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/constructor.go:185 +0x34a
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x22e6488, 0x1bb38c0}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x22e6488, 0x188f220}, {0xc0000b1640, 0x4, 0x4}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*constructorNode).Call(0xc0005b8a80, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/constructor.go:155 +0x137
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x22e6488, 0x1add220}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x22e6488, 0x188f1c0}, {0xc0000b1c80, 0x4, 0x4}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*constructorNode).Call(0xc0005b8cc0, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/constructor.go:155 +0x137
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x22e6488, 0x1b82c80}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:287 +0x34a
go.uber.org/dig.paramList.BuildList({{0x22e6488, 0x18c22a0}, {0xc0000a6a50, 0x5, 0x5}}, {0x22de3f0, 0xc00037c8c0})
	go.uber.org/dig@v1.17.1/param.go:150 +0xad
go.uber.org/dig.(*Scope).Invoke(0xc00037c8c0, {0x18c22a0, 0x20cf338}, {0x0, 0x0, 0x31ace60?})
	go.uber.org/dig@v1.17.1/invoke.go:122 +0x318
go.uber.org/dig.(*Container).Invoke(0x20?, {0x18c22a0?, 0x20cf338?}, {0x0?, 0xc0002487c0?, 0xc0005196a0?})
	go.uber.org/dig@v1.17.1/invoke.go:82 +0x25
go.uber.org/fx.runInvoke({0x7f6412c73c68?, 0xc0005b4148?}, {{0x18c22a0, 0x20cf338}, {0xc00026cf00, 0x7, 0x8}})
	go.uber.org/fx@v1.22.1/invoke.go:109 +0x153
go.uber.org/fx.(*module).executeInvoke(0xc0004d6270, {{0x18c22a0, 0x20cf338}, {0xc00026cf00, 0x7, 0x8}})
	go.uber.org/fx@v1.22.1/module.go:320 +0x145
go.uber.org/fx.(*module).executeInvokes(0xc0004d6270)
	go.uber.org/fx@v1.22.1/module.go:306 +0xda
go.uber.org/fx.New({0xc000519b08, 0x7, 0x0?})
	go.uber.org/fx@v1.22.1/app.go:517 +0x9fa
github.com/divyam234/teldrive/cmd.runApplication(0xc0004a2000)
	github.com/divyam234/teldrive/cmd/run.go:133 +0x617
github.com/divyam234/teldrive/cmd.NewRun.func1(0xc0004a4000?, {0x1bc71b8?, 0x4?, 0x1bc71bc?})
	github.com/divyam234/teldrive/cmd/run.go:47 +0x17
github.com/spf13/cobra.(*Command).execute(0xc0004a0308, {0x3233760, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004a0008)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(0x22bc0e0?, {0x22bc2a0?, 0xc0005bb100?})
	github.com/spf13/cobra@v1.8.1/command.go:1034 +0x47
main.main()
	./main.go:15 `+0x96`

**Comment by SingingDalong** [comment]
Neon DB can only be used up to version 1.4.9.

**Comment by iwconfig** [comment]
- [Read the admonition in the release note for 1.4.10](https://github.com/divyam234/teldrive/releases/tag/1.4.10)
- [Migrate to another databse system that supports `proonga`](https://github.com/divyam234/teldrive/issues/312#issuecomment-2237119505)
