### ISSUE TITLE
[BUG] folder name bug with same name as subdir

### ISSUE THREAD

**Issue by phanirithvij** [divyam234/teldrive#319]
To reproduce

make directory `test` and make directory `test/test` and try to visit the `test/test` and the url doesn't change in the UI.

**Comment by divyam234** [comment]
@phanirithvij  this issue  its related to this https://github.com/divyam234/teldrive/issues/304

**Comment by phanirithvij** [comment]
Ok I'll check it out. What about #309

**Comment by divyam234** [comment]
its also related to that

**Comment by phanirithvij** [comment]
Ok I'll try the db migration.

**Comment by phanirithvij** [comment]
Ok, I'm not sure how to do the migration, I changed to the pgroonga 15 (ver same as before) postgres in docker compose.
I noticed a bug with the db where a new `root` row was created and was able to recover file system structure by just dropping that.

But this particular issue still exists in the UI.

![image](https://github.com/user-attachments/assets/36378f63-321e-41dd-9cd1-50b0d19567e1)

As you can see in the breadcrumbs it is showing a single `a` not two `a > a`

**Comment by divyam234** [comment]
fixed in latest build
