### ISSUE TITLE
Issue in logging in via reverse proxy using domain name

### ISSUE THREAD

**Issue by ajeshbs** [divyam234/teldrive#32]
I am facing an issue while attempting to app hosted on an Nginx server using a domain name that's been set up with a reverse proxy. I can access the application and successfully log in by using the application’s direct IP address and port (http://xxx.xx.xx.xx:8080/login), but when I attempt to do the same via our domain name (https://files.xxx.xe/login), I am unable to log in.

**Comment by divyam234** [comment]
@ajeshbs  check your nginx config you should enable websockets  on reverse proxy or use caddy server for hosting better than nginx

**Comment by ajeshbs** [comment]
yup Thanks,enabling websockets in my nginx config works 
Added these lines: 

`proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";`

To location
