### ISSUE TITLE
[Feature Request] AArch64 Support for Teledrive

### ISSUE THREAD

**Issue by ImLoadingUuU** [divyam234/teldrive#324]
It would be good if theres AArch64 Support.
It means you can run teldrive on Raspberry Pi or Other ARM64 Linux Devices.

**Comment by Crypt0x69** [comment]
There are already Bins for AARCH64.

[teldrive-1.4.16-linux-arm64.tar.gz](https://github.com/divyam234/teldrive/releases/download/1.4.16/teldrive-1.4.16-linux-arm64.tar.gz)
