### ISSUE TITLE
what  is APP_ID and APP_HASH?

### ISSUE THREAD

**Issue by 2640123** [divyam234/teldrive#37]
what mean is 'Use official ones'?and how can i got it

**Comment by divyam234** [comment]
@2640123  see updated docs or join discord people can help you there for setup

**Comment by 2640123** [comment]
> @2640123 see updated docs or join discord people can help you there for setup


ok,i got this,but I still can't access the web, I'm still researching

btw,Is it possible to connect to rclone in the future?

**Comment by TangentFoxy** [comment]
This information is no longer in the documentation.

**Comment by TangentFoxy** [comment]
An [old version of the docs specified that these are the API ID and API HASH for your Telegram account](https://pkg.go.dev/github.com/divyam234/teldrive), which are just misnamed here. They can be accessed from my.telegram.org
