### ISSUE TITLE
Multi Channel upload not working

### ISSUE THREAD

**Issue by xd003** [divyam234/teldrive#42]
I have recreated this issue many times on a totally fresh server, newly created database & and clean teldrive docker container to ensure that its not any sort of issue on my end. I have created 2 new channels called demo1 and demo2 and will be adding 2 bots in each of the channel for this test & will try to upload demo1.mp4 and demo2.mp4 in each of the channel respectively

1) Once the teldrive container is running successfully, i open the web UI and set demo1 channel as default and add 2 bots in it, then set demo2 channel as default and 2 bots in it
2) i set demo1 channel as default and upload demo1.mp4 through web - successful
3) i set demo2 channel as default and upload demo2.mp4 through web - ```callback: rpcDoRequest: rpc error code 400: CHANNEL_INVALID```

**Comment by hackmonker** [comment]
Can confirm to be facing this error on my end also. ```callback: rpcDoRequest: rpc error code 400: CHANNEL_INVALID```

**Comment by ben-ba** [comment]
still present;

rclone debug;
`
pacer: low level retry 5/10 (error HTTP error 500 (500 Internal Server Error) returned body: "{"error":"callback: rpcDoRequest: rpc error code 400: CHANNEL_INVALID"}")`
teldrive log:
`
teldrive  | Error #01: callback: rpcDoRequest: rpc error code 400: CHANNEL_INVALID
teldrive  | [GIN] 2023/11/15 - 11:17:03 | 500 |  185.728763ms |    xx.xx.xx.xx | POST     "/api/uploads/4714f372dxxxxxxxxxxxx3544b6c459c3f?channelId=xxxxxxxxx&fileName=b4918b227xxxxxxxx00c542d7b034&partNo=1"`

**Comment by ben-ba** [comment]
https://github.com/divyam234/teldrive/blob/fa7735dbe93e7eb3df634e1379c9e7bc1d2379a0/services/upload.service.go#L125

the upload service get all bots by your user id and choose the next one, so with luck the right one gets picked

**Comment by xd003** [comment]
@ben-ba Really appreciate your findings

So again clearing up the steps to reproduce this using rclone since teldrive-cli is now depreciated
 ( I know this is a issue with teldrive itself & not rclone or uploader-cli but stil... )

1) Create multiple channels & add different bots to all channels 
2) Now create multiple remotes in rclone, each remote having different `channel_id` option 
3) Trying uploading files to all the remotes. Upload with fail with errors mentioned just couple of messages above.
