### ISSUE TITLE
rclone bug

### ISSUE THREAD

**Issue by martysl** [divyam234/teldrive#48]
i comppiled rclone from https://github.com/divyam234/rclone on ubuntu 
2023-10-11 16:50:11 DEBUG : 00000-1170173422.png(0xc000113000): >_readAt: n=0, err=vfs reader: failed to write to cache file: HTTP error 400 (400 Bad Request) returned body: "misssing hash\n"

2023-10-11 16:50:12 DEBUG : 00000-1170173422.png(0xc000113000): >close: err=<nil>
2023-10-11 16:50:12 INFO  : /00000-1170173422.png: GET from [::1]:46302
Errors:               120 (retrying may help)
i tried http sftp and webdav it not work command was:
rclone -P serve  http --addr :3234 td: --vfs-cache-mode full  -vvv --transfers=10 --multi-thread-streams=16 --vfs-cache-max-age=24h
my url: https://martynka-teldrive.hf.space/
please help

**Comment by devcrono** [comment]
On Ubuntu you need to mark rclone as executable, and run it like this: sudo ./rclone AND THE COMMAND

**Comment by martysl** [comment]
sadly no, sudo not help ;/

**Comment by devcrono** [comment]
friend, in ubuntu you first need to install it from the OFFICIAL repository
then you locate the modified one, which is this one, start it manually from within a specific folder e.g. Download folder would look like this
I created a folder within donwloas named rclone.

cd /home/_USER_/Download/rclone (enter)

now command to start

sudo ./rclone config (enter)
FOLLOW THE STEPS ON THE SCREEN

here it will configure the drive, and the first step for teldrive to work with rclone

**Comment by martysl** [comment]
thank you for your repluy and sorry about my english and etc:
i did all steps (with sudo) including compile rclone from your repo, so its installed then i did rclone config set remote name td and follow steps from was need, then i run command 
rclone -P serve  webdav --addr :3434 td: --vfs-cache-mode full  -vvv --transfers=10 --multi-thread-streams=16 --vfs-cache-max-age=24h
remote url was https://martynka-teldrive.hf.space also tired https://martynka-teldrive.hf.space/api and also localy in docker pc but same situation its latest release of teldrive, i will try later with older version, someone mention 1.06 work well
 anyway thanks for any sugestion and your great work
