### ISSUE TITLE
Share links

### ISSUE THREAD

**Issue by mdznf** [divyam234/teldrive#6]
Will you add this feature in the future. To share the links of the files with friends for example. I tested it and the upload is super fast with bots, around 30-40MB/s. But I don't see the option for share like in teledive. Good job and keep it up

**Comment by divyam234** [comment]
I haven't use teledrive so didn't know about this feature.Can you elaborate how this in teledrive

**Comment by mdznf** [comment]
![imagen](https://github.com/divyam234/teldrive/assets/80652301/bbad8a95-1254-4dc1-8e30-c39b64cc4dc5)
that is how it works in teledrive. I don't know how can it be implemented in your script

**Comment by divyam234** [comment]
It will be easier to implement.I will  give a option for rate limiting in env file to prevent users from being soft banned in next build.How many tokens you used concurrently btw.Moreover best way to prevent bans is to use official telegram client appid and apphash instead of personal appid

**Comment by mdznf** [comment]
Ok, and where I can get those appid and apphash? I have 5 bots in my private channel now. I'm using personal from my dot telegram dot org/apps

**Comment by divyam234** [comment]
Those are fetched using reverse engineering official clients

**Comment by mdznf** [comment]
Ok, I talked to you on discord, if you can help me over there. Regards. Hoping you implement this feature soon in the future
