### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by CloverHQ** [divyam234/teldrive#61]
![image](https://github.com/divyam234/teldrive/assets/26052169/4a6bab4d-37e9-42d8-81fb-26e4e1376243)
ws take too long

**Comment by CloverHQ** [comment]
[GIN] 2023/11/09 - 19:14:43 | 404 |      78.017µs |  45.128.232.152 | CONNECT  ""
[GIN] 2023/11/09 - 19:14:52 | 200 |      69.631µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 19:14:53 | 200 |     107.184µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 19:16:59 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:17:18 | 200 |         2m24s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:20:36 | 200 |     373.516µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 19:20:37 | 200 |     118.182µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 19:20:59 | 200 |       106.1µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 19:21:00 | 200 |      39.553µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 19:21:02 | 200 |      56.691µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 19:21:02 | 200 |      21.543µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 19:21:05 | 200 |      88.802µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 19:21:06 | 200 |      109.84µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 19:23:01 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:23:23 | 200 |         2m21s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:23:26 | 200 |         2m23s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:23:28 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 19:48:52 | 404 |      323.32µs |  45.128.232.125 | CONNECT  ""
[GIN] 2023/11/09 - 21:54:50 | 404 |      259.69µs |  45.128.232.125 | CONNECT  ""
[GIN] 2023/11/09 - 22:05:33 | 200 |     969.622µs |   218.81.64.177 | GET      "/login"
[GIN] 2023/11/09 - 22:05:34 | 200 |      79.129µs |   218.81.64.177 | GET      "/api/auth/session"
[GIN] 2023/11/09 - 22:07:57 | 200 |         2m23s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:10:56 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:12:09 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:12:11 | 200 |         2m21s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:12:11 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:12:12 | 200 |         2m23s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:18:32 | 200 |         2m22s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:22:07 | 200 |     352.181µs |   78.108.177.52 | GET      "/"
[GIN] 2023/11/09 - 22:29:47 | 200 |         2m25s |   218.81.64.177 | GET      "/api/auth/ws"
[GIN] 2023/11/09 - 22:29:52 | 200 |         2m23s |   218.81.64.177 | GET      "/api/auth/ws"

**Comment by ben-ba** [comment]
is your teldrive behind a reverse proxy?

**Comment by CloverHQ** [comment]
> is your teldrive behind a reverse proxy?

no reverse proxy, it may be an IP problem

**Comment by devcrono** [comment]
Are you making the connection, by name or by IP? Do you have an explicit port? 

Let's eliminate the cases

**Comment by CloverHQ** [comment]
> Are you making the connection, by name or by IP? Do you have an explicit port?
> 
> Let's eliminate the cases

by ip, The website can be accessed normally but the websocket cannot be accessed

**Comment by devcrono** [comment]
update the version, delete teldrive.db and try to do it either through Firefox or Chrome

**Comment by rHohith** [comment]
check system time is as local time, that solved for me
