### ISSUE TITLE
rclone copy broken

### ISSUE THREAD

**Issue by ben-ba** [divyam234/teldrive#64]
1. upload a file on the teldrive webgui
2. download it on the teldrive webgui
3. list it with rclone; rclone ls teldrive:
4. try to download it with rclone; rclone copy teldrive:

webgui download works, list with rclone works, but copy through the following error;

rclone;

> user@linux: ./docker/teldrive$ rclone ls teldrive:
> 2922470 test.jpg
> user@linux: ./docker/teldrive$ rclone copy teldrive: .
> 2023/11/19 22:50:05 ERROR : test.jpg: Failed to copy: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:05 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:06 ERROR : test.jpg: Failed to copy: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:06 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:07 ERROR : test.jpg: Failed to copy: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:07 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"
> 2023/11/19 22:50:07 Failed to copy: failed to open source object: HTTP error 400 (400 Bad Request) returned body: "invalid hash\n"

teldrive - rclone download:
`
teldrive  | [GIN] 2023/11/19 - 21:50:07 | 400 |  101.728746ms |    xxxxxxxxxxxx| GET      "/api/files/test.jpg?hash=72a203c4225f2a1f1601f2bb15f574ef"
`

teldrive - webgui download:
`
teldrive  | [GIN] 2023/11/19 - 21:53:23 | 200 |  1.031847122s |    xxxxxxxxxxxx | GET      "/api/files/test.jpg?hash=37bb8dba5ce6b11456c640ac248f3751&d=1"
`

Maybe the only question is, why are the hash values are different?

**Comment by ben-ba** [comment]
just realized, that copy isn't implemented (yet), "only" the server side copy.
so no bug, nothing broken, maybe a hint/reminder for other guys and a future request ;)

**Comment by musahi0128** [comment]
You are not using correct value for `access_token` or the latest version of rclone for teldrive

**Comment by ben-ba** [comment]
rclone version is 1.64.3, so the latest teldrive version
access_token have to be right, because ls and a client to server copy works....

**Comment by musahi0128** [comment]
If so, then your session on that token has been expired. Also try change one characters from your `access_token` after the first 5 characters and see if ls works. Also try restarting your instance. It sounds weird because my rclone copy work just fine.
![msedge_u86OPNfJuU](https://github.com/divyam234/teldrive/assets/9418340/089541d0-3f23-4da6-8b18-8d1e33012da8)

**Comment by ben-ba** [comment]
It's weird; with changed session token and restarted teldrive;

> rclone copy teldrive: -P .
> 2023/11/20 09:23:07 Failed to create file system for "teldrive:": invalid session token

**Comment by musahi0128** [comment]
Try this
1. Stop teldrive
2. Delete teldrive.db
3. Start teldrive
4. Do a fresh login
5. Get your new user-session
6. Try again with the copy and show us what's happened on the log when/if the copy failed again

**Comment by ben-ba** [comment]
Thanks, with your previous hint, i grabbed a new session token and now it works. 
It's still weird for me, because the rclone ls worked.

**Comment by ben-ba** [comment]
Solution: Update the access_token for rclone.

**Comment by ben-ba** [comment]
Solution: Update the access_token for rclone.
