### ISSUE TITLE
i got it to work once but now am getting this error, please help

### ISSUE THREAD

**Issue by aniel300** [divyam234/teldrive#68]
i got it to work once but now am getting this error, please help @divyam234 
![image](https://github.com/divyam234/teldrive/assets/7571729/58bd78e2-9049-4e10-8a28-9f185b5eab47)

**Comment by aniel300** [comment]
> if you restarted the docker, you will have to see again the ip that postgresql is working, that is your error @aniel300

it stays the same '172.18.0.7" however for my understanding i can use "172.18.0.1" which is what am using

**Comment by ben-ba** [comment]
u shouldn't work with ips in an docker environment.

**Comment by aniel300** [comment]
i was able to fix it by adding "xxx:port number"
