### ISSUE TITLE
Can't list root folder (a.k.a `my-drive` content on the webUI)

### ISSUE THREAD

**Issue by ylorn** [divyam234/teldrive#75]
I just upgrade my `teldrive` to the `1.0.15` and the modded `rclone` (I will refer it as `tclone` from now on) to the `1.65.1`, and suddenly neither the webUI nor the `tclone lsd` command lists the content of the root folder. However, the content still exists, because I can list the subfolder by directly using its path.

### On webUI
The root folder `my-drive` is empty:
<img width="2012" alt="Screenshot 2023-12-09 at 1 07 27 AM" src="https://github.com/divyam234/teldrive/assets/1502810/ab2e867f-68d0-435e-b1ed-00f0cd064633">

However, assessing a known subfolder works fine:
<img width="2012" alt="Screenshot 2023-12-09 at 1 07 40 AM" src="https://github.com/divyam234/teldrive/assets/1502810/243a3292-2cfd-42d1-88ac-1a9c05413832">

### On modded `rclone`:
It shows empty result when trying to list the root folder content:

```sh
tclone lsd td:
```
<img width="396" alt="Screenshot 2023-12-09 at 1 16 34 AM" src="https://github.com/divyam234/teldrive/assets/1502810/1de92171-0b84-4211-8841-a847e3f54e20">

However, the content is listed correctly if a valid subpath is provided to the command:

```sh
tclone lsd td:Resource
```
<img width="495" alt="Screenshot 2023-12-09 at 1 19 13 AM" src="https://github.com/divyam234/teldrive/assets/1502810/844845ae-7487-46ad-98a4-2efc5a3fc9bd">

I am not sure if this is a bug or is there any action I need to take. Please let me know, thanks!

**Comment by ddomino007** [comment]
i have this happening too!

**Comment by divyam234** [comment]
Don't move files from UI it's broken will be fixed in next build use rclone instead

**Comment by ylorn** [comment]
> Don't move files from UI it's broken will be fixed in next build use rclone instead

Duly noted. Thanks!
