### ISSUE TITLE
Accessing non-existent folders via manual URLs

### ISSUE THREAD

**Issue by joseavilasg09** [divyam234/teldrive#8]
Hi. I've come across an issue with dynamic routes. It appears that it's possible to manually input URLs in the address bar that lead to non-existent folders, as shown in the attached image

![routes](https://github.com/divyam234/teldrive/assets/84698658/427a0782-0f6b-431d-ab87-4c028e0ec5f2)

**Comment by divyam234** [comment]
It's can be fixed by creating a custom error page if path doesn't exists but I will need server to send some type of message object that path doesn't exceed exists.Currently I am bit occupied but pull request are welcome if you want to contribute.

**Comment by joseavilasg09** [comment]
@divyam234 Alright. I'll try to do that. Thanks.

**Comment by joseavilasg09** [comment]
Changes were made and this issue has been fixed in #9. So closing this issue.
