### ISSUE TITLE
any version after 1.0.15 of the container doesn't work for me

### ISSUE THREAD

**Issue by aniel300** [divyam234/teldrive#85]
any version after 1.0.15 of the container doesn't work for me, please advise.

**Comment by xd003** [comment]
Specify the exact error with steps to reproduce it. Your description is very vague

**Comment by aniel300** [comment]
> Specify the exact error with steps to reproduce it. Your description is very vague

i will do

**Comment by aniel300** [comment]
> #UNRELATED
> 
> 1. Kindly give a clearer guide on how to set this up on VPS
> 2. Also, I would like to know if there is support for URL upload

i will try to help u

**Comment by aniel300** [comment]
after updating to latest today issue seem to have been fixed, closing.
