### ISSUE TITLE
net/http: HTTP/1.x transport connection broken error triggers rclone re-downloads, which again can trigger downloadQuotaExceeded

### ISSUE THREAD

**Issue by steffen-poulsen** [divyam234/teldrive#86]
When uploading files to teldrive with rclone, sometimes teldrive repeatedly throws this error for some file uploads, "net/http: HTTP/1.x transport connection broken: http: ContentLength=1048576000 with Body length 0":

```
2023/12/23 08:37:56 DEBUG : pacer: low level retry 7/10 (error Post "http://192.168.1.5:8080/api/uploads/26f5a8517edb<...uploadid>?channelId=<channelid>&encrypted=false&fileName=<filename>.mp4&partName=82998fe49ab74<...partname>&partNo=2": net/http: HTTP/1.x transport connection broken: http: ContentLength=1048576000 with Body length 0)
2023/12/23 08:37:56 DEBUG : pacer: Rate limited, increasing sleep to 5s
```

This error triggers a low-level retry in rclone, which means that the source file will now be downloaded again.

Unfortunately, some backends doesn't appreciate this behaviour of downloading the same file rapidly over and over very much, and they will soon throw an error. E.g. the google drive backend throws a 403 with "downloadQuotaExceeded":

`Failed to copy: failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded`

This error means that your google drive account will now be in a 24h cool-down period, before you can use download any files from it again.

The only unusual activity I see in logs/teldrive.log are errrors like this:

`{"level":"error","ts":"2023-12-23T07:53:56.132Z","logger":"uploads","msg":"uploadFile","error":"callback: upload part: send upload part 802 RPC: retry middleware skip: rpcDoRequest: rpc error code 400: FILE_PART_SIZE_INVALID","errorVerbose":"callback:\n    github.com/gotd/td/telegram.(*Client).Run.func3\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/connect.go:151\n  - upload part:\n    github.com/gotd/td/telegram/uploader.(*Uploader).bigLoop.func2\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:109\n  - send upload part 802 RPC:\n    github.com/gotd/td/telegram/uploader.(*Uploader).uploadBigFilePart\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:38\n  - retry middleware skip:\n    github.com/divyam234/teldrive/internal/retry.(*retry).Handle.retry.Handle.func1\n        /app/internal/retry/retry.go:34\n  - rpcDoRequest:\n    github.com/gotd/td/internal/mtproto.(*Conn).Invoke\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/internal/mtproto/rpc.go:44\n  - rpc error code 400: FILE_PART_SIZE_INVALID"}`

The default number of low-level retries in rclone is set to 10, it can be lowered to i.e. 3 using this argument:

`--low-level-retries 3`

A value of 3 seems to be low enough that the ban from the re-downloads will not be triggered, and still high enough that most of the regularly needed retries against the google drive backend will still succeed.

**Comment by steffen-poulsen** [comment]
Today I got another variant, RPC_MCGET_FAIL / RPC_CALL_FAIL.

Btw, I still got the downloadQuotaExceeded error, even with the reduced `--low-level-retries ` argument. I have now set up the google drive source backend as a cached backend instead, let's see if that helps :-)

```
rclone.log:

2023/12/25 03:55:40 DEBUG : pacer: low level retry 1/3 (error HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: upload part: send upload part 1298 RPC: retry middleware skip: rpcDoRequest: rpc error code 500: RPC_MCGET_FAIL\"}")

2023/12/25 03:56:55 DEBUG : pacer: low level retry 2/2 (error Post "http://192.168.1.5:8080/api/uploads/<uploadid>?channelId=<channelid>&encrypted=false&fileName=<filename>&partName=<partname>&partNo=3": net/http: HTTP/1.x transport connection broken: http: ContentLength=1048576000 with Body length 336990208)

2023/12/25 03:56:56 DEBUG : <filename>: Received error: Post "http://192.168.1.5:8080/api/uploads/<uploadid>?channelId=<channelid>&encrypted=false&fileName=<filename>&partName=<partname>&partNo=3": net/http: HTTP/1.x transport connection broken: http: ContentLength=1048576000 with Body length 336990208 - low level retry 0/2

2023/12/25 04:17:25 DEBUG : pacer: low level retry 1/3 (error HTTP error 500 (500 Internal Server Error) returned body: "{\"code\":500,\"message\":\"callback: upload part: send upload part 1549 RPC: retry middleware skip: rpcDoRequest: rpc error code 500: RPC_CALL_FAIL\"}")

logs/teldrive.log:

{"level":"error","ts":"2023-12-25T03:17:25.517Z","logger":"uploads","msg":"uploadFile","error":"callback: upload part: send upload part 1549 RPC: retry middleware skip: rpcDoRequest: rpc error code 500: RPC_CALL_FAIL","errorVerbose":"callback:\n    github.com/gotd/td/telegram.(*Client).Run.func3\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/connect.go:151\n  - upload part:\n    github.com/gotd/td/telegram/uploader.(*Uploader).bigLoop.func2\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:109\n  - send upload part 1549 RPC:\n    github.com/gotd/td/telegram/uploader.(*Uploader).uploadBigFilePart\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:38\n  - retry middleware skip:\n    github.com/divyam234/teldrive/internal/retry.(*retry).Handle.retry.Handle.func1\n        /app/internal/retry/retry.go:34\n  - rpcDoRequest:\n    github.com/gotd/td/internal/mtproto.(*Conn).Invoke\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/internal/mtproto/rpc.go:44\n  - rpc error code 500: RPC_CALL_FAIL"}

{"level":"error","ts":"2023-12-25T03:18:09.282Z","logger":"uploads","msg":"uploadFile","error":"callback: upload part: send upload part 398 RPC: retry middleware skip: rpcDoRequest: rpc error code 400: FILE_PART_SIZE_INVALID","errorVerbose":"callback:\n    github.com/gotd/td/telegram.(*Client).Run.func3\n /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/connect.go:151\n  - upload part:\n    github.com/gotd/td/telegram/uploader.(*Uploader).bigLoop.func2\n /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:109\n  - send upload part 398 RPC:\n    github.com/gotd/td/telegram/uploader.(*Uploader).uploadBigFilePart\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/telegram/uploader/big.go:38\n  - retry middleware skip:\n    github.com/divyam234/teldrive/internal/retry.(*retry).Handle.retry.Handle.func1\n        /app/internal/retry/retry.go:34\n  - rpcDoRequest:\n    github.com/gotd/td/internal/mtproto.(*Conn).Invoke\n        /go/pkg/mod/github.com/gotd/td@v0.91.0/internal/mtproto/rpc.go:44\n  - rpc error code 400: FILE_PART_SIZE_INVALID"}


```

**Comment by divyam234** [comment]
@steffen-poulsen  RPC_MCGET_FAIL / RPC_CALL_FAIL these are appearing from latest telegram  api layer updates  something telegram, have changed from their side . I add add those as exception errors for retries in next build.

**Comment by steffen-poulsen** [comment]
Great! - thanks! :-)

**Comment by aniel300** [comment]
@steffen-poulsen did u ever fixed this? am having the same issue
