### ISSUE TITLE
Error 500 default channel not set

### ISSUE THREAD

**Issue by py7hon** [divyam234/teldrive#88]
Can you make to auto set Default Channel or Create new Channel after login for uploading because without set the Channel get error 500.

```term
24/12/2023 04:17 PM     ERROR   uploads uploadFile      {"error": "default channel not set", "errorVerbose": "default channel not set\ngithub.com/divyam234/teldrive/pkg/services.GetDefaultChannel\n\t/app/pkg/services/common.go:265\ngithub.com/divyam234/teldrive/pkg/services.(*UploadService).UploadFile\n\t/app/pkg/services/upload.go:153\ngithub.com/divyam234/teldrive/pkg/controller.(*Controller).UploadFile\n\t/app/pkg/controller/upload.go:41\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/pkg/middleware.Authmiddleware\n\t/app/pkg/middleware/authjwt.go:50\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/api.InitRouter.RecoveryWithZap.CustomRecoveryWithZap.func2\n\t/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:159\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/api.InitRouter.Ginzap.GinzapWithConfig.func1\n\t/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:59\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
```

**Comment by ylorn** [comment]
got the same error after upgrading to `1.0.18`

**Comment by rHohith** [comment]
ERROR   uploads uploadFile      {"error": "default channel not set", "errorVerbose": "default channel not set\ngithub.com/divyam234/teldrive/pkg/services.GetDefaultChannel\n\tgithub.com/divyam234/teldrive/pkg/services/common.go:265\ngithub.com/divyam234/teldrive/pkg/services.(*UploadService).UploadFile\n\tgithub.com/divyam234/teldrive/pkg/services/upload.go:153\ngithub.com/divyam234/teldrive/pkg/controller.(*Controller).UploadFile\n\tgithub.com/divyam234/teldrive/pkg/controller/upload.go:41\ngithub.com/gin-gonic/gin.(*Context).Next\n\tgithub.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/pkg/middleware.Authmiddleware\n\tgithub.com/divyam234/teldrive/pkg/middleware/authjwt.go:50\ngithub.com/gin-gonic/gin.(*Context).Next\n\tgithub.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/api.InitRouter.RecoveryWithZap.CustomRecoveryWithZap.func2\n\tgithub.com/gin-contrib/zap@v0.2.0/zap.go:159\ngithub.com/gin-gonic/gin.(*Context).Next\n\tgithub.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/divyam234/teldrive/api.InitRouter.Ginzap.GinzapWithConfig.func1\n\tgithub.com/gin-contrib/zap@v0.2.0/zap.go:59\ngithub.com/gin-gonic/gin.(*Context).Next\n\tgithub.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\tgithub.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\tgithub.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2938\nnet/http.(*conn).serve\n\tnet/http/server.go:2009\nruntime.goexit\n\truntime/asm_amd64.s:1650"}

**Comment by rHohith** [comment]
After Logining in to teldrive
- [ ] Click On your profile photo
- [ ] Then Settings
- [ ] Set Default Channel

This must solve your issue

**Comment by tarbib** [comment]
thank you @rHohith 
Btw I don't get the purpose of choosing a channel. what is it for?
