### ISSUE TITLE
Downloads fail when using bots, because the telegram api returns empty messages.

### ISSUE THREAD

**Issue by hoptional** [divyam234/teldrive#92]
Hi, 

When I try to download any of my files I get an internal server error.

The following error is logged:

> teldrive     | 25/12/2023 11:05 PM      ERROR   [Recovery from panic]   {"time": "25/12/2023 11:05 PM", "error": "interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message", "request": "GET /api/files/fwXkleFNFa30ETYM/stream/jcajqh6586oum5vt1dfrhmpofjbacp9k2f3vdji0raj55qgjutcid16lkpi5vdckhhpd3jn76qse2?hash=a2cf7f10b89e59bf8f5c175a6ca474a7&d=1 HTTP/1.1\r\nHost: localhost:19919\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\r\nCache-Control: max-age=0\r\nConnection: keep-alive\r\nCookie: user-session=REDACTED\r\nSec-Ch-Ua: \"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Microsoft Edge\";v=\"120\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0\r\n\r\n", "stack": "goroutine 168383 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/divyam234/teldrive/api.InitRouter.RecoveryWithZap.CustomRecoveryWithZap.func2.1()\n\t/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:147 +0x330\npanic({0x162e1c0?, 0xc00017cc60?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngithub.com/divyam234/teldrive/pkg/services.getParts({0x1de9698, 0xc00149e800}, 0x1dd1f40?, 0xc000afe000, {0xc0001aab10, 0xa})\n\t/app/pkg/services/common.go:161 +0x547\ngithub.com/divyam234/teldrive/pkg/services.(*FileService).GetFileStream(0xc001580048, 0xc00149e800)\n\t/app/pkg/services/file.go:614 +0x14d6\ngithub.com/divyam234/teldrive/pkg/controller.(*Controller).GetFileStream(...)\n\t/app/pkg/controller/file.go:101\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00149e800)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b\ngithub.com/divyam234/teldrive/api.InitRouter.RecoveryWithZap.CustomRecoveryWithZap.func2(0xc000827488?)\n\t/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:159 +0x78\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00149e800)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b\ngithub.com/divyam234/teldrive/api.InitRouter.Ginzap.GinzapWithConfig.func1(0xc00149e800)\n\t/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:59 +0xb1\ngithub.com/gin-gonic/gin.(*Context).Next(...)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001a0340, 0xc00149e800)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001a0340, {0x1de7738?, 0xc0002188c0}, 0xc0015c6000)\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd\nnet/http.serverHandler.ServeHTTP({0xc001ef3920?}, {0x1de7738?, 0xc0002188c0?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc0046fecf0, {0x1de9548, 0xc00025eb70})\n\t/usr/local/go/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 1\n\t/usr/local/go/src/net/http/server.go:3086 +0x5cb\n"}

This happens both when trying to download with the browser (tried Firefox and Edge) and via the rclone fork.

I am using the docker image of version 1.0.18.

**Comment by hoptional** [comment]
So I investigated a bit and found that the error only happens when I use bots. Seems like the bots only get an empty message from the telegram api. If I remove all bot tokens the downloads start to work again.

Do my bots need any special setup? All of them appear as admin with in the group with all permissions except for "Remain anonymous " and "Add new admins".

**Comment by hoptional** [comment]
Update:  I realized that I was using a group instead of a channel. I completely forgot that there is a difference between the two. I switched to a channel and now everything is working fine.

Thank you very much for this amazing project!

**Comment by wes1993** [comment]
Hello @hoptional,
I'm in the situation... could you please tell me how can I switch from Group to Channel?

Thanks a lot
Stefano

**Comment by hoptional** [comment]
I don't think this is possible, unfortunately. I just created a new channel and started from scratch.

**Comment by wes1993** [comment]
Damn, Thanks i need to migrate all the messages i think :-D
