### ISSUE TITLE
TelDrive (Chonky)

### ISSUE THREAD

**Issue by Pe0xonN** [divyam234/teldrive#93]
I have a question about how to implement into TelDrive (Chonky)

**Comment by ben-ba** [comment]
chonky or conky?

**Comment by PLoliwi** [comment]
o to mi chodzi https://github.com/TimboKZ/Chonky


> chonky or conky?

**Comment by Pe0xonN** [comment]
> chonky or conky?

https://github.com/TimboKZ/Chonky

**Comment by ben-ba** [comment]
rclone mount + https://chonky.io/docs/2.x/basics/folder-chain

**Comment by Pe0xonN** [comment]
> rclone mount + https://chonky.io/docs/2.x/basics/folder-chain

How to import it to the teldrive website

**Comment by joseavilasg** [comment]
@Pe0xonN Teldrive Web UI is already using chonky

**Comment by Pe0xonN** [comment]
> @Pe0xonN Teldrive Web UI is already using chonky

But there is no view of the photos and does that somehow turn it on

**Comment by Pe0xonN** [comment]
@divyam234

**Comment by Pe0xonN** [comment]
> @divyam234

Is there any way to enable preview PNG jpg photos

**Comment by azeyrx** [comment]
It might work somehow, but especially with larger folders, you would probably quickly hit the rate limit, which is likely why it's not implemented.
