### ISSUE TITLE
Issues with >100MB on Cloudflare

### ISSUE THREAD

**Issue by CakesTwix** [divyam234/teldrive#95]
When uploading files larger than 100MB to TelDrive, a 413 error is thrown, which means the entity is too large.
No such problems on NextCloud.

**Comment by azeyrx** [comment]
Nextcloud also divides the files into much smaller "parts", teldrive divides the files into at least 500MB packages each, which is then canceled by the limitation on the part of Cloudflare.

**Comment by Mak5er** [comment]
![зображення](https://github.com/divyam234/teldrive/assets/98599732/a0073430-5581-4564-991e-954a9916e23a)
This problem is due to cloudflare settings

**Comment by CakesTwix** [comment]
@Mak5er, I know, it's a paid feature

**Comment by Mak5er** [comment]
> @Mak5er, I know, it's a paid feature

By the way, do you know of any analogues where this is free?
